### PR TITLE
Supervise the maker's ping actor 

### LINKED ISSUE #2103: Maker `ping` actor panics upon startup
I saw this several times when running the maker locally:

```
/Users/dakami/.cargo/bin/cargo run --color=always --manifest-path maker testnet
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s
     Running [,,,]
2022-05-24 10:03:51  INFO shared_bin::logger: Initialized logger
2022-05-24 10:03:51  INFO maker: Running version: 0.4.16-114-ge5f77cc
2022-05-24 10:03:51  INFO maker: CFDs created with this release will settle after 24 hours
2022-05-24 10:03:51  INFO maker: Authentication details: username='itchysats' password='0fac8291a04e51c1a0459e82a36a084f45a4abffc9ddf5cc111c36370c30e52a'
2022-05-24 10:03:51  INFO maker: Connection details: maker_id='10d4ba2ac3f7a22da4009d813ff1bc3f404dfe2cc93a32bedf1512aa9951c95e', peer_id='12D3KooWDjzHna3pNi1Bt1DoRfrpsBREykJKXDRDxXvhJNAdDZEk'
2022-05-24 10:03:51  INFO daemon::db: Opened database at maker/testnet/maker.sqlite
thread 'rocket-worker-thread' panicked at 'we just started: ActorShutdown', xtra-libp2p-ping/src/ping.rs:63:34
stack backtrace:
2022-05-24 10:03:51  INFO maker::connection: Listening on 0.0.0.0:9999
2022-05-24 10:03:51 DEBUG libp2p_tcp: listening on 0.0.0.0:10000    
2022-05-24 10:03:51 DEBUG libp2p_tcp: New listen address: /ip4/127.0.0.1/tcp/10000    
2022-05-24 10:03:51 DEBUG libp2p_tcp: New listen address: /ip4/192.168.1.10/tcp/10000    
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: <xtra_libp2p_ping::ping::Actor as xtra::Actor>::started::{{closure}}
             at /Users/dakami/CoBloX/repos/hermes/xtra-libp2p-ping/src/ping.rs:63:20
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
   7: xtra::context::Context<A>::run::{{closure}}
             at /Users/dakami/.cargo/git/checkouts/xtra-092fb79b35830946/81cb91b/src/context.rs:225:33
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:289:9
  10: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/catch_unwind.rs:36:42
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  12: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  13: ___rust_try
  14: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  15: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  16: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/catch_unwind.rs:36:9
  17: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/remote_handle.rs:105:29
2022-05-24 10:03:52 DEBUG maker::actor_system: Maker actor system ready
2022-05-24 10:03:52 DEBUG bitmex_stream: Connecting to BitMex realtime API
2022-05-24 10:03:52  INFO http: HTTP interface is ready endpoint=http://127.0.0.1:8001
  18: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/task/core.rs:161:17
  19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/loom/std/unsafe_cell.rs:14:9
  20: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/task/core.rs:151:13
2022-05-24 10:03:52 DEBUG daemon::oracle: Fetching announcement event_id=/x/BitMEX/BXBT/2022-05-24T18:00:00.price?n=20
```

Panic is at this line:

https://github.com/itchysats/itchysats/blob/93c31033a41b76996e2486ef5972fedeb7c576bb/xtra-libp2p-ping/src/ping.rs#L63

Is this related to how we create and spawn the actor? I thought this can never happen?

### PR DESCRIPTION
**Pull request by luckysori**
This serves two overlapping purposes:

1. Keep the `ping::Actor` alive by not dropping its only strong `xtra::Address`.
2. Restart the `ping::Actor` if it is ever stopped or panics.

Point 1 therefore means that this PR:

Fixes https://github.com/itchysats/itchysats/issues/2103.

### CODE REVIEW

File: xtras/src/supervisor.rs [hunk 1]
```diff
@@ -18,6 +18,7 @@ pub struct Actor<T, R> {
     ctor: Box<dyn Fn() -> T + Send + 'static>,
     tasks: Tasks,
     restart_policy: Box<dyn FnMut(&R) -> bool + Send + 'static>,
+    _actor: Address<T>, // kept around to ensure that the supervised actor stays alive
```
Comment (klochowicz) [inline xtras/src/supervisor.rs:21]: love the general solution to all supervised actors! 👍

**Review by klochowicz — APPROVED** [review]
great work, thanks for tackling this so fast

**Review by da-kami — APPROVED** [review]
