### PR TITLE
Initiate timeout for the maker's collab settlement

### LINKED ISSUE #1668: Collaborative settlement "stuck"
testnet setup, id: `14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e`

```
2022-03-23 12:06:47	
{"timestamp":"2022-03-23T01:06:47.727244104Z","level":"INFO","fields":{"message":"Received rollover proposal","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e"},"target":"daemon::rollover_maker"}
	
2022-03-23 12:06:47	
{"timestamp":"2022-03-23T01:06:47.726861305Z","level":"INFO","fields":{"message":"Received rollover proposal from taker","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e","taker_id":"175ea037ab00d4e4ca2cc5d8ee314d0cf49443b2743f63d25be6046fb0fbae05"},"target":"daemon::maker_cfd"}
	
2022-03-23 12:04:30	
{"timestamp":"2022-03-23T01:04:30.47204264Z","level":"WARN","fields":{"message":"Failed to handle settlement proposal: Settlement for order 14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e is already in progress: The address is still connected","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e"},"target":"daemon::maker_cfd"}
	
2022-03-23 12:01:47	
{"timestamp":"2022-03-23T01:01:47.733323266Z","level":"WARN","fields":{"message":"Rollover failed: Failed to execute command on CFD: Cannot roll over while CFD is in collaborative settlement","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e"},"target":"model::cfd"}
	
2022-03-23 12:01:47	
{"timestamp":"2022-03-23T01:01:47.690020832Z","level":"INFO","fields":{"message":"Received rollover proposal","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e"},"target":"daemon::rollover_maker"}
	
2022-03-23 12:01:47	
{"timestamp":"2022-03-23T01:01:47.689813915Z","level":"INFO","fields":{"message":"Received rollover proposal from taker","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e","taker_id":"175ea037ab00d4e4ca2cc5d8ee314d0cf49443b2743f63d25be6046fb0fbae05"},"target":"daemon::maker_cfd"}
	
2022-03-23 11:04:30	
{"timestamp":"2022-03-23T00:04:30.429478626Z","level":"INFO","fields":{"message":"Received settlement proposal","taker_id":"175ea037ab00d4e4ca2cc5d8ee314d0cf49443b2743f63d25be6046fb0fbae05","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e","price":"42328"},"target":"daemon::collab_settlement_maker"}
```

The automation did accept the settlement:

```
	2022-03-23 12:11:37	
{"timestamp":"2022-03-23T01:11:37.478622188Z","level":"WARN","fields":{"message":"Action already issued","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e","action":"AcceptSettlement"},"target":"itchy_automation::itchysats::feed"}
	
2022-03-23 12:11:37	
{"timestamp":"2022-03-23T01:11:37.451805126Z","level":"DEBUG","fields":{"message":"Sending action","url":"http://maker:8000/api/cfd/14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e/acceptSettlement","body":"\"acceptSettlement\""},"target":"itchy_automation::itchysats::client"}
	
2022-03-23 12:11:37	
{"timestamp":"2022-03-23T01:11:37.443859929Z","level":"INFO","fields":{"message":"Accepting settlement","order_id":"14ee9d24-615b-4ed7-9ee7-7e05e9f95e9e","counterparty":"175ea037ab00d4e4ca2cc5d8ee314d0cf49443b2743f63d25be6046fb0fbae05","quantity":"100","margin":"0.00238184 BTC"},"target":"itchy_automation::itchysats"}
```

I think the problem must be in the daemon then. Somehow the collab settlement got stuck, but I don't see any related errors in the daemon.
Note that this is not the only CFD that seems to have run into this problem
I think there is some bug in collab settlement
I don't see any errors or warnings that would point to the concrete problem. Only have the behaviour.

### PR DESCRIPTION
**Pull request by da-kami**
If the taker never comes back to the maker with an `Initiate` message the maker's collaborative settlement actor will never finish.
We add a timeout after accept that ensures that we receive an `Initiate` message within 60 seconds after accepting.
Upon receiving `Initiate` we record that `Initiate` was received.

If the timeout is reached we only abort if `Initiate` was not received, because if it was received we can be sure the actor will finish.

### CODE REVIEW

File: daemon/src/collab_settlement_maker.rs [hunk 1]
```diff
@@ -225,3 +287,11 @@ impl Actor {
             .await;
     }
 }
+
+/// Message sent from the spawned task to `collab_settlement_taker::Actor` to
```
Comment (luckysori) [inline daemon/src/collab_settlement_maker.rs]:
```suggestion
/// Message sent from the spawned task to `collab_settlement_maker::Actor` to
```

**Review by luckysori — APPROVED** [review]

File: daemon/src/collab_settlement_maker.rs [hunk 2]
```diff
@@ -72,6 +87,37 @@ impl Actor {
...
+            .executor
+            .execute(self.proposal.order_id, |cfd| {
+                Ok(cfd.fail_collaborative_settlement(anyhow!(
+                    "Taker did not initiate within {timeout} seconds"
+                )))
+            })
+            .await
+        {
+            tracing::warn!(
+                "Failed to execute `fail_collaborative_settlement` command: {:#}",
```
Comment (bonomat) [inline daemon/src/collab_settlement_maker.rs]: would be nice to include the order_id in the log message.

**Review by bonomat — APPROVED** [review]
👍

File: daemon/src/collab_settlement_maker.rs [hunk 3]
```diff
@@ -195,6 +243,20 @@ impl Actor {
...
+        let timeout = {
+            let this = ctx.address().expect("self to be alive");
+            async move {
+                tokio::time::sleep(INITIATE_TIMEOUT).await;
+
+                this.send(InitiateTimeoutReached {
+                    timeout: INITIATE_TIMEOUT,
+                })
+                .await
+                .expect("can send to ourselves");
```
Comment (thomaseizinger) [inline daemon/src/collab_settlement_maker.rs]: It is unlikely that this happens because our `Tasks` are tied to the lifetime of the actor but I think it would be safer here to just `_` the result. If we can't send this message than the actor is disappeared which means it doesn't matter anymore.

**Review by thomaseizinger — APPROVED** [review]

File: daemon/src/collab_settlement_maker.rs (hunk 3 above)
Comment (da-kami) [reply daemon/src/collab_settlement_maker.rs]: Note: I aligned removing `expect` from the other actor impls, see latest commit.

**Review by thomaseizinger — APPROVED** [review]

**Comment by bonomat** [comment]
3 approvals. I go ahead and merge this. 

bors r+
