### PR TITLE
Calculate liquidation price for short position

### LINKED ISSUE #1589: Liquidation price for short is wrong
Looks like there is an error when calculating the short liquidation price : 

image

says: 

```
Liquidation | $27,635
```

but it should be something very high.

### PR DESCRIPTION
**Pull request by bonomat**
Resolves #1589

Note: the order in the UI has the wrong liquidation price since it still relies on global params which only takes long position into account. This will be fixed in #1582

### CODE REVIEW

**Comment by bonomat** [comment]
tests are correct: there is an issue :) converted to draft and will work on it

**Comment by bonomat** [comment]
Ready for review @da-kami / @klochowicz

File: model/src/cfd.rs [hunk 1]
```diff
@@ -1435,6 +1432,17 @@ pub fn calculate_long_liquidation_price(leverage: Leverage, price: Price) -> Pri
     price * leverage / (leverage + 1)
 }
 
+/// calculates short liquidation price
+///
+/// Note: if leverage == 1, then the liquidation price will go towards infinity.
+/// This is represented as Price::INFINITE
+pub fn calculate_short_liquidation_price(leverage: Leverage, price: Price) -> Price {
+    if (leverage - 1) == 0 {
```
Comment (da-kami) [inline model/src/cfd.rs]: Any reason why you are not using the `Leverage::ONE` constant? 
To make the division by `0` more obvious? I think it would still read better using the constant...

**Review by da-kami — APPROVED** [review]

File: model/src/cfd.rs (hunk 1 above)
Comment (bonomat) [reply model/src/cfd.rs]: `Leverage - Leverage` does not make much sense because (imho) `Leverage-Leverage` should return `Leverage` but `Leverage::new` does not allow `0`, which means, a naive implementation of `impl Sub<Leverage> for Leverage` would not work.

Comment (da-kami) [reply model/src/cfd.rs]: I am confused by your answer.
Why not this condition:

```suggestion
    if leverage == Leverage::ONE {
```

Comment (bonomat) [reply model/src/cfd.rs]: ah, yea, that would work 😅
