### PR TITLE
bdk 0.17

### LINKED ISSUE #1821: Investigate regression after bumping `bdk` to version `0.17`
We want to keep depending on latest `bdk` but it appears that upgrading to `0.17` stopped our wallet from finding UTXOs. Perhaps we need to use the updated APIs differently or open an issue on `bdk` if the APIs no longer support our needs.

---

Original problem: https://github.com/itchysats/itchysats/issues/1814.

Bump to `bdk:0.17.0`: https://github.com/itchysats/itchysats/pull/1655.

Temporary fix: #1817.

### PR DESCRIPTION
**Pull request by bonomat**
Should fix #1821

If we want to ensure that more addresses are cached, then we need to call it explicitly:  https://github.com/bitcoindevkit/bdk/commit/45767fcaf7c65d5020f99fdc35c147acd6e8d037

### CODE REVIEW

File: daemon/src/wallet.rs [hunk 1]
```diff
@@ -135,6 +135,8 @@ impl Actor<ElectrumBlockchain> {
 
 impl Actor<ElectrumBlockchain> {
     fn sync_internal(&mut self) -> Result<WalletInfo> {
+        self.wallet.ensure_addresses_cached(1000)?;
```
Comment (klochowicz) [inline daemon/src/wallet.rs:138]: perhaps it would be worthwhile to expose this as an optional CLI parameter? In case we run into trouble with calculating wallet balance, we would be able to restart with a little tweak to the parameters instead of cutting a new release

**Review by klochowicz — APPROVED** [review]
great find!

**Review by luckysori — APPROVED** [review]
Looking at the `bdk` code we thought this wouldn't work for some reason, but I trust your judgement. And obviously the PR you link to indicates that it should. Thanks for looking into this!

File: daemon/src/wallet.rs (hunk 1 above)
Comment (bonomat) [reply daemon/src/wallet.rs:138]: I dont' think this is necessary. I'd rather make this dynamic and increase slowly until this maximum is reached.

**Comment by bonomat** [comment]
> Looking at the `bdk` code we thought this wouldn't work for some reason, but I trust your judgement. And obviously the PR you link to indicates that it should. Thanks for looking into this!

Did I miss something? Why wouldn't it work ?

**Comment by da-kami** [comment]
> > Looking at the `bdk` code we thought this wouldn't work for some reason, but I trust your judgement. And obviously the PR you link to indicates that it should. Thanks for looking into this!
> 
> Did I miss something? Why wouldn't it work ?

Because of the cache size being a constant of `100` addresses in `sync`:

https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L1575

and the fact that `ensure_addresses_cached` does not seem to use any other source to set this to a different number:

https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L354-L390

Maybe we missed something though. Following the code there is not easy and we did not evaluate it in detail. But might be worth having another look ;)
You could take the `taker_master`'s `testnet` wallet and try if the balance is being picked up using the code on this branch. We had problems with that recently, that's why we reverted the upgrade.

**Review by da-kami — CHANGES_REQUESTED** [review]
Thanks for having another go at this!
I'd say we should only merge this after we successfully tested that the testnet setup's `taker_master` wallet balance was picked up correctly. I think it should not be too hard to test that locally. Might be a bit annoying, but I really want to avoid that we run into a problem where user's balances are `0` 😬

**Comment by klochowicz** [comment]
> Thanks for having another go at this!
> I'd say we should only merge this after we successfully tested that the testnet setup's `taker_master` wallet balance was picked up correctly. I think it should not be too hard to test that locally. Might be a bit annoying, but I really want to avoid that we run into a problem where user's balances are `0` 😬

I'd say merging after release will give us plenty of time to iterate on the fix if for some reason it won't work. I agree, let's not rush it 👍

**Comment by bonomat** [comment]
> > > Looking at the `bdk` code we thought this wouldn't work for some reason, but I trust your judgement. And obviously the PR you link to indicates that it should. Thanks for looking into this!
> > 
> > 
> > Did I miss something? Why wouldn't it work ?
> 
> Because of the cache size being a constant of `100` addresses in `sync`:
> 
> [https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L1575](https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs?rgh-link-date=2022-04-22T00%3A12%3A37Z#L1575)
> 
> and the fact that `ensure_addresses_cached` does not seem to use any other source to set this to a different number:
> 
> [https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L354-L390](https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs?rgh-link-date=2022-04-22T00%3A12%3A37Z#L354-L390)
> 
> Maybe we missed something though. Following the code there is not easy and we did not evaluate it in detail. But might be worth having another look ;) You could take the `taker_master`'s `testnet` wallet and try if the balance is being picked up using the code on this branch. We had problems with that recently, that's why we reverted the upgrade.

That's why we call it explicitly now which should have the same effect as before no?

**Comment by da-kami** [comment]
> > > > Looking at the `bdk` code we thought this wouldn't work for some reason, but I trust your judgement. And obviously the PR you link to indicates that it should. Thanks for looking into this!
> > > 
> > > 
> > > Did I miss something? Why wouldn't it work ?
> > 
> > 
> > Because of the cache size being a constant of `100` addresses in `sync`:
> > [https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L1575](https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs?rgh-link-date=2022-04-22T00%3A12%3A37Z#L1575)
> > and the fact that `ensure_addresses_cached` does not seem to use any other source to set this to a different number:
> > [https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs#L354-L390](https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/mod.rs?rgh-link-date=2022-04-22T00%3A12%3A37Z#L354-L390)
> > Maybe we missed something though. Following the code there is not easy and we did not evaluate it in detail. But might be worth having another look ;) You could take the `taker_master`'s `testnet` wallet and try if the balance is being picked up using the code on this branch. We had problems with that recently, that's why we reverted the upgrade.
> 
> That's why we call it explicitly now which should have the same effect as before no?

If you look at the code, then you see that `sync` calls `ensure_addresses_cached` with a constant of `100` addresses. I think that our call to `ensure_addresses_cached` with `1000` addresses does not change anything in the code. But maybe I'm mistaken. Did you have a look at the code?
Previously we passed the `1000` addresses to `sync`directly (which is now not possible anymore because the signature of `sync` changed)!

**Comment by da-kami** [comment]
> > Thanks for having another go at this!
> > I'd say we should only merge this after we successfully tested that the testnet setup's `taker_master` wallet balance was picked up correctly. I think it should not be too hard to test that locally. Might be a bit annoying, but I really want to avoid that we run into a problem where user's balances are `0` 😬
> 
> I'd say merging after release will give us plenty of time to iterate on the fix if for some reason it won't work. I agree, let's not rush it 👍

Yeah, I'm fine with testing it on `testnet` after the release. We don't have to invest the time to test locally then, but might still be a good option because the feedback cycle is way shorter.

**Comment by bonomat** [comment]
Yes, I did ;)

when calling `ensure_addresses_cached` we generate `X` addresses and store them in the db. When syncing this db is read and checked against the blockchain. 

Initially `ensure_addresses_cached` we passed in `1000` to the call `wallet.sync` which called `ensure_addresses_cached`. Now, we call `ensure_addresses_cached` with `1000` before and again with `100` inside `wallet.sync`. 

Not sure what you are referring to or usnure about?

**Review by da-kami — APPROVED** [review]
might still want to wait until the release is out to avoid potential problems related to the upgrade (not necessarily just the wallet)

**Comment by bonomat** [comment]
btw: 0.18 is out 😅 https://github.com/bitcoindevkit/bdk/releases/tag/v0.18.0

**Review by thomaseizinger — APPROVED** [review]
Nice! Missed that in my original commit.

Would you mind squashing so we don't have a broken commit in the history?
