### PR TITLE
Rollover 2.0

### LINKED ISSUE #1622: Make `ProposeRollover` more explicit
When rolling over both parties need to know from where they are rollingover from and to when/what they are rollingover to. If one of the values is different, the rollover might fail at a very late step e.g. when verifying the signatures. 

Right now, these values are assumed, i.e. both parties think they will rollover for another 24h, from the "last successful" rollover, handle their own feeAccount and subtract the feeAmounts, etc. 

We should make the `ProposeRollover` message more explicit in regards to where do we rollover from and until do we rollover to. That way we can ensure that both parties are talking about the same thing before starting with the actual protocol. 

Differently said, we (either party) should tell the other party the params they are going to use for the rollover. 

More discussion on this topic: https://github.com/itchysats/itchysats/discussions/1726

## Annoyance counter

- 01/04/2022: Rollover not being explicit leads to several rollover failures which leads to unintended publication of old states which triggers unimplemented revoke behaviour. This came up in https://github.com/itchysats/itchysats/pull/1715.
- 01/04/2022: Closed https://github.com/itchysats/itchysats/issues/1039 in favor of this one.
- 01/04/2022: Closed https://github.com/itchysats/itchysats/issues/1617 in favor of this one.

### PR DESCRIPTION
**Pull request by da-kami**
This implements a more resilient rollover protocol where the taker proposes a `commit_txid` from which to roll over from to the maker. Protocol details can be found here: https://github.com/itchysats/itchysats/issues/1775

TODO:

- [x] Assert on the exact fees at the end of the rollover tests, make sure that the fees did not change compared to the code on master.
- [x] Add actor tests where we rollover twice and on the second rollover the taker uses the same `event_id`. (This might be a bit tricky)

Resolves [#1622](https://github.com/itchysats/itchysats/issues/1622), https://github.com/itchysats/itchysats/issues/1775

--- 

Implications when merging this PR and rolling it into production:

Previous ItchySats version that included the `libp2p` `rollover` protocol will not be compatible because the protocol contains breaking changes. Since we did *not* roll any version that included `libp2p` `rollover` out on Umbrel there should not be any users affected. 
The legacy rollover should not be affected by the breaking changes. The feature was implemented in a way that is backwards compatible (to the legacy version). This has to be tested on `testnet`.

### CODE REVIEW

File: daemon/src/projection.rs [hunk 1]
```diff
@@ -418,12 +418,22 @@ impl Cfd {
...
-                self.aggregated.fee_account =
-                    self.aggregated.fee_account.add_funding_fee(funding_fee);
+
+                if let Some(complete_fee) = complete_fee {
+                    self.aggregated.fee_account =
+                        self.aggregated.fee_account.from_complete_fee(complete_fee);
+                } else {
+                    self.aggregated.fee_account =
+                        self.aggregated.fee_account.add_funding_fee(funding_fee);
+                }
```
Comment (bonomat) [inline daemon/src/projection.rs]: Is clippy not complaining about this? I think it would be nicer to use a `match` statement.

File: daemon/src/rollover/taker.rs [hunk 2]
```diff
@@ -270,8 +272,13 @@ impl Actor {
                                 .into_rollover_msg()?
                                 .try_into_msg2()?;
 
-                            let revoked_commit =
-                                finalize_revoked_commits(&dlc, own_cfd_txs.commit.1, msg2)?;
+                            // TODO: Shouldn't the adaptor sig be the one of the dlc.commit_tx?
```
Comment (bonomat) [inline daemon/src/rollover/taker.rs]: You might be right: we want to store the _revoked_ commit signatures, i.e. the one from the last commit transaction which should be in `dlc.commit`. @luckysori : what do you think ? 
Was this is a bug?

**Comment by da-kami** [comment]
Note concerning this comment https://github.com/itchysats/itchysats/issues/1775#issuecomment-1162610819:

The current tests are actually not affected because it's implement in a way that if the current active `event_id` from the `dlc` is picked the maker does not apply the check if the `event_id` is already expired. This is the same as the previous behavior.

Once we add more tests where the taker pricks a previous `commit_txid` for the rollover we would run into this problem though.

File: sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql [hunk 3]
```diff
@@ -0,0 +1,19 @@
+ALTER TABLE
+    rollover_completed_event_data
+ADD
+    -- The complete fee including this rollover (contrary to the funding_fee this field contains the accumulated fees until now).
+    COLUMN complete_fee text NULL;
```
Comment (bonomat) [inline sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql]: I think this should be `INTEGER`

File: sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+ALTER TABLE
+    rollover_completed_event_data
```
Comment (bonomat) [inline sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql:7]: You could also combine these two alter statements: 

```
ALTER TABLE
    rollover_completed_event_data
ADD
    COLUMN complete_fee text NULL,
    COLUMN complete_fee_flow text NULL;
```

File: sqlite-db/src/closed.rs [hunk 5]
```diff
@@ -297,8 +297,16 @@ impl ClosedCfdInputAggregate {
...
             RolloverAccepted => {}
             RolloverRejected => {}
-            RolloverCompleted { dlc, funding_fee } => {
-                self.fee_account = self.fee_account.add_funding_fee(funding_fee);
+            RolloverCompleted {
+                dlc,
+                funding_fee,
+                complete_fee,
+            } => {
+                if let Some(complete_fee) = complete_fee {
```
Comment (bonomat) [inline sqlite-db/src/closed.rs]: same as earlier, I think it would be nicer to have match statements

File: sqlite-db/src/models.rs [hunk 6]
```diff
@@ -901,3 +901,138 @@ impl From<Settlement> for model::Settlement {
...
 }
+
+#[derive(Copy, Clone, Debug, PartialEq, sqlx::Type)]
+pub enum FeeFlow {
+    LongPaysShort,
+    ShortPaysLong,
+    None,
+}
+
+pub fn into_complete_fee(
```
Comment (bonomat) [inline sqlite-db/src/models.rs:912]: Maybe this can be changed to a `impl From` block?

```
impl From<(Option<FeeFlow>, Option<i64>) for Option<model::CompleteFee> {

}
```

File: daemon/src/rollover/protocol.rs [hunk 7]
```diff
@@ -232,22 +231,22 @@ pub enum CompleteFee {
...
-impl From<FeeFlow> for CompleteFee {
-    fn from(fee_flow: FeeFlow) -> Self {
-        match fee_flow {
-            FeeFlow::LongPaysShort(a) => CompleteFee::LongPaysShort(a),
-            FeeFlow::ShortPaysLong(a) => CompleteFee::ShortPaysLong(a),
-            FeeFlow::Nein => CompleteFee::Nein,
+impl From<model::CompleteFee> for CompleteFee {
+    fn from(complete_fee: model::CompleteFee) -> Self {
+        match complete_fee {
+            model::CompleteFee::LongPaysShort(a) => CompleteFee::LongPaysShort(a),
```
Comment (bonomat) [inline daemon/src/rollover/protocol.rs:239]: I'm dreaming of a world where we get rid of `LongPaysShort` and `ShortPaysLong` terminology and just express everything with positive and negative numbers...

File: model/src/cfd.rs [hunk 8]
```diff
@@ -898,10 +898,64 @@ impl Cfd {
...
+        } else {
+            match dlc
+                .revoked_commit
+                .iter()
+                .find(|revoke_commit| revoke_commit.txid == from_tx_id)
+            {
+                Some(revoke_commit) => revoke_commit.settlement_event_id.ok_or_else(|| anyhow!(
+                    "Proposed commit-txid {} not eligible for rollover because no event-id attached", from_tx_id
+                ))?,
+                None => bail!("Unknown commit-txid {} proposed by taker", from_tx_id),
```
Comment (bonomat) [inline model/src/cfd.rs]: This error would mean the taker has a commit-txid the maker doesn't know about right? Meaning, the taker succeeded in a former rollover but the maker failed?

File: model/src/cfd.rs [hunk 9]
```diff
@@ -913,14 +967,25 @@ impl Cfd {
...
         let candidate_event_id = olivia::next_announcement_after(now + self.settlement_interval);
+
+        let from_event_id = if let Some(from_event_id) = from_event_id {
+            from_event_id
+        } else {
+            self.dlc
+                .as_ref()
+                .context("Cannot roll over without DLC")?
+                .settlement_event_id
+        };
```
Comment (bonomat) [inline model/src/cfd.rs]: I think this would benefit from a short comment why we are taking `self.dlc.settlement_event_id`.

File: model/src/cfd.rs [hunk 10]
```diff
@@ -913,14 +967,25 @@ impl Cfd {
...
+
         let hours_to_charge = match version {
             rollover::Version::V1 => 1,
             rollover::Version::V2 => self.hours_to_extend_in_rollover(now)?,
-            rollover::Version::V3 => {
-                self.hours_to_extend_in_rollover_based_on_event(candidate_event_id, now)?
-            }
+            rollover::Version::V3 => self.hours_to_extend_in_rollover_based_on_event(
+                candidate_event_id,
```
Comment (bonomat) [inline model/src/cfd.rs]: Below you rename the arg to `to_event_id`. I think it might be worth also renaming it here.

File: model/src/cfd.rs [hunk 11]
```diff
@@ -913,14 +967,25 @@ impl Cfd {
         }
 
         let now = OffsetDateTime::now_utc();
-
         let candidate_event_id = olivia::next_announcement_after(now + self.settlement_interval);
+
+        let from_event_id = if let Some(from_event_id) = from_event_id {
+            from_event_id
+        } else {
```
Comment (bonomat) [inline model/src/cfd.rs]: What do you think of adding a log message saying that this is a retry? 
That way we can track how often a rollover is being retried.

**Review by bonomat — APPROVED** [review]
Good job. A few minor comments but overall concept should be sound

File: sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql (hunk 4 above)
Comment (da-kami) [reply sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql:7]: I tried, but could not get it working. I think this it unfortunately not possible in `sqlite`, see: 

https://stackoverflow.com/questions/6172815/sqlite-alter-table-add-multiple-columns-in-a-single-statement
https://www.sqlite.org/lang_altertable.html

File: daemon/src/rollover/protocol.rs (hunk 7 above)
Comment (da-kami) [reply daemon/src/rollover/protocol.rs:239]: I am not sure that will make the code easier to read and understand, but feel free to refactor this at some point :)

File: model/src/cfd.rs (hunk 8 above)
Comment (da-kami) [reply model/src/cfd.rs]: Yes. Given that the maker now fires and forgets the last message this should never happen, unless the `maker` fails on the "last mile", e.g. when saving `RolloverCompleted` into the database.
I don't think we can overcome that problem without the maker messaging the taker about a failure. 
The taker could then roll-over from the previous event, but I am not sure about the security assumptions for such a scenario. Definitely out of scope for now.

File: daemon/src/rollover/taker.rs (hunk 2 above)
Comment (da-kami) [reply daemon/src/rollover/taker.rs]: I added this TODO on the way when I noticed this, thanks for reacting! I will move this into a separate PR so we can discuss it in context!

File: sqlite-db/src/models.rs (hunk 6 above)
Comment (da-kami) [reply sqlite-db/src/models.rs:912]: After giving this a quick try: Not possible because `Option` is not defined within the crate so we run into:

```
Only traits defined in the current crate can be implemented for arbitrary types [E0117]
```

I don't think there is a way around this at the moment - if you know one let me know :)

File: model/src/cfd.rs (hunk 9 above)
Comment (da-kami) [reply model/src/cfd.rs]: This is what was previously picked (inside the function `hours_to_extend_in_rollover_based_on_event`) but I'm happy to add a comment!

File: sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql (hunk 4 above)
Comment (bonomat) [reply sqlite-db/migrations/20220622055305_add_complete_fee_to_rollover_tables.sql:7]: oh, learned something new today. Thanks for links.

File: sqlite-db/src/models.rs (hunk 6 above)
Comment (bonomat) [reply sqlite-db/src/models.rs:912]: oh well, you could probably simplify it to

```
impl From<(FeeFlow, i64) for model::CompleteFee {

}
```

but feel free to leave as is.

File: model/src/cfd.rs (hunk 11 above)
Comment (da-kami) [reply model/src/cfd.rs]: Note: I added the statement when we `start` the rollover because I think it makes more sense to log the information there. 
At this point in time we cannot say for sure if it is a retry, because the `start_rollover_maker` logic sets the `from_event_id` also when it is the current one. I implemented it this way because I think it makes the feature more complete. The fact that we have to evaluate if `from_event_id` is `Some` in `accept_rollover_proposal` is just due to being backwards compatible. 

In the future we can opt for making the `settlement_event_id` always set in `RevokeCommit`, i.e. remove the `Option` and then this check for `Some` in `accept_rollover_proposal` would go away.

File: sqlite-db/src/models.rs (hunk 6 above)
Comment (da-kami) [reply sqlite-db/src/models.rs:912]: I'd have to deal with the `Options` multiple times upon conversion then, because this code is re-used by two tables.
The `Options` are actually quite annoying - and only needed to be backwards compatible. I think I'll leave it for now and focus on the tests

File: daemon/src/rollover/taker.rs (hunk 2 above)
Comment (da-kami) [reply daemon/src/rollover/taker.rs]: see https://github.com/itchysats/itchysats/pull/2280

File: daemon/src/rollover/protocol.rs (hunk 7 above)
Comment (klochowicz) [reply daemon/src/rollover/protocol.rs:239]: We had that in the beginning, didn't we? then we decided that it will be easier and less confusing to use this terminology. Happy to move back to positive and negative numbers, as long as we have a clear doc where we state explicitly what is what.

**Comment by da-kami** [comment]
Totally worth adding the rollover retry test (https://github.com/itchysats/itchysats/pull/2272/commits/615fc6955f8eb85791b28241d89fad2a5255238e)! I found several bugs and missing parts on the way! 

Retry from a previous `commit_txid` is tested now, we can opt for adding even more extensive tests to also test what happens if we go back multiple rollovers - but the internal logic to pick the `from_event_id` and `from_complete_fee` is the same, so I expect it to behave the same!

File: daemon/src/rollover/maker.rs [hunk 12]
```diff
@@ -120,28 +122,32 @@ impl Actor {
...
                 cfd.verify_counterparty_peer_id(&peer.into())?;
-                cfd.start_rollover()
+                cfd.start_rollover_maker(propose.from_commit_txid)
             })
             .await
         {
-            tracing::warn!(%order_id, "Rollover failed after handling taker proposal: {e:#}");
+            Ok(event_id) => event_id,
+            Err(e) => {
+                tracing::warn!(%order_id, "Rollover failed after handling taker proposal: {e:#}");
```
Comment (da-kami) [inline daemon/src/rollover/maker.rs:135]: Note: I think we should change this into a `reject` scenario. The maker can send a `reject` back to the taker at this point. 

I did not change this yet because I am not sure about side-effects (I think they should be minimal, but still).

File: daemon/src/rollover/protocol.rs (hunk 7 above)
Comment (da-kami) [reply daemon/src/rollover/protocol.rs:239]: > We had that in the beginning

IMHO this is only half of the truth - what we had initially was incomplete. To make it complete we introduced `FeeAccount` and other structs on the way. I acknowledge that changing the logic of`+` and `-` instead to an `enum` might mean more code, but I would be careful stating that it can easily be made "better" by using `+` and `-`. We re-wrote this code three times already. 

 I am happy to see another refactoring to this part as long as it has at least the same test coverage that we have now :)

File: daemon/src/rollover/maker.rs (hunk 12 above)
Comment (da-kami) [reply daemon/src/rollover/maker.rs:135]: see https://github.com/itchysats/itchysats/issues/2294

File: daemon/src/rollover/taker.rs [hunk 13]
```diff
@@ -51,6 +53,8 @@ impl xtra::Actor for Actor {
 pub struct ProposeRollover {
     pub order_id: OrderId,
     pub maker_peer_id: PeerId,
+    pub from_commit_txid: Txid,
+    pub from_settlement_event_id: BitMexPriceEventId,
 }
```
Comment (klochowicz) [inline daemon/src/rollover/taker.rs:58]: why not be explicit and also state `until_settlement_event_id` here as well? Then it would be unambiguous until when we could extend the rollover?
I believed that what #1622 originally imagined too.

File: model/src/cfd.rs [hunk 14]
```diff
@@ -780,7 +784,10 @@ impl Cfd {
         self.commit_tx.is_some()
     }
 
-    pub fn can_auto_rollover_taker(&self, now: OffsetDateTime) -> Result<(), NoRolloverReason> {
+    pub fn can_auto_rollover_taker(
+        &self,
+        now: OffsetDateTime,
+    ) -> Result<(Txid, BitMexPriceEventId), NoRolloverReason> {
```
Comment (klochowicz) [inline model/src/cfd.rs:790]: it would be great to introduce some type that discribes this tuple, because it's pretty random in this context.

for example:
```rust
struct RolloverStartParams {
from_commit_tx: Txid,
from_settlement_event_id: BitMexPriceEventId
}
```

File: model/src/cfd.rs [hunk 15]
```diff
@@ -894,10 +903,74 @@ impl Cfd {
...
+        let event = CfdEvent::new(self.id, EventKind::RolloverStarted);
+
+        Ok((event, from_event_id, from_complete_fee))
+    }
+
     pub fn accept_rollover_proposal(
         self,
         tx_fee_rate: TxFeeRate,
         funding_rate: FundingRate,
+        from_params: Option<(BitMexPriceEventId, CompleteFee)>,
```
Comment (klochowicz) [inline model/src/cfd.rs:973]: again, it's unfortunate to send `None`. Rust can be really descriptive, it would be nicer to send an enum that clarifies this better :)

File: model/src/cfd.rs [hunk 16]
```diff
@@ -1538,15 +1643,15 @@ impl Cfd {
...
+        let to_settlement_time = to_event_id.timestamp();
+        let time_to_extend = to_settlement_time - from_settlement_time;
 
         let hours_to_extend = time_to_extend.whole_hours();
 
         if !hours_to_extend.is_positive() {
             bail!(
-                "Cannot rollover if candidate event ID is no later than current event ID:
-                 {candidate_settlement_time} <= {current_settlement_time}",
+                "Cannot rollover if to event ID is not later than from event ID:
```
Comment (klochowicz) [inline model/src/cfd.rs:1653]: nit: "to" and "from" don't read too well. perhaps "until" instead of "to" would make it easier? 

or maybe "start" and "end" as a pair?

File: model/src/cfd.rs [hunk 17]
```diff
@@ -2216,6 +2331,10 @@ pub struct RevokedCommit {
     // To monitor revoked commit transaction
     pub txid: Txid,
     pub script_pubkey: Script,
+    // To enable the taker to rollover from a previous commit-tx
+    // The maker requires these parameters to reason about the previous commit
+    pub settlement_event_id: Option<BitMexPriceEventId>,
+    pub complete_fee: Option<CompleteFee>,
```
Comment (klochowicz) [inline model/src/cfd.rs]: this comment has a high likelihood to become stale (maybe we could extract a struct where we could put these 2 fields, so that it will never get out of place?)

File: model/src/cfd.rs [hunk 18]
```diff
@@ -3345,15 +3465,15 @@ mod tests {
     #[test]
     fn given_current_settlement_in_12_hours_and_candidate_in_19_then_7_hour_extension() {
         for now in common_time_boundaries() {
-            let current_event_id = BitMexPriceEventId::with_20_digits(now + 12.hours());
-            let candidate_event_id = BitMexPriceEventId::with_20_digits(now + 19.hours());
```
Comment (klochowicz) [inline model/src/cfd.rs:3349]: actually, "current" and "candidate" naming sounds pretty good too. I wouldn't mind having this one throughout.

**Review by klochowicz — APPROVED** [review]
I have added some comments, but nothing blocking; happy to fix most of the nitpicks myself in a follow-up. 

concept ACK.

File: daemon/src/rollover/taker.rs (hunk 13 above)
Comment (da-kami) [reply daemon/src/rollover/taker.rs:58]: The maker already tells the taker what event to use. I am not sure what value it would have to add it to the taker's proposal.

File: model/src/cfd.rs (hunk 17 above)
Comment (da-kami) [reply model/src/cfd.rs]: fair enough, I changed it into more descriptive doc comments

**Comment by da-kami** [comment]
I am happy to see the rest of the changes in follow-ups. Will see to squash and bors this.

File: model/src/cfd.rs (hunk 15 above)
Comment (da-kami) [reply model/src/cfd.rs:973]: Note that all these are only `Option`s because of backwards compatibility for the legacy protocol versions. 

I would hope to clean that up once we are a few versions ahead. If you feel strong about it feel free to do a small refactoring round as a follow up!

File: model/src/cfd.rs (hunk 18 above)
Comment (da-kami) [reply model/src/cfd.rs:3349]: Yeah, I am not super happy with `to` and `from` neither, but I found `candidate` super confusing, because for me it indicates that it is only a candidate but might not be used (i.e. something else would be used instead). That's not what we want to express here. It's literally a to-from scenario (from a cost perspective, as in the hours from and to you get charged for). Happy to see a follow up on that that changes it throughout (but please not candidate :)
