### PR TITLE
Drop connection to peer on yamux connection error

### LINKED ISSUE #2554: Improve `Endpoint` resilience to drop "stale" connections on the `maker`
@holzeis and me were able to reproduce a problem where the taker becomes unavailable ungracefully there are scenarios where the maker's endpoint is not notified with `ConnectionDropped`.
We were able to reproduce this by killing the `taker` process on the raspi. The `maker` did not receive a connection drop in such a case. 

This behavior results in the endpoint and protocol actors assuming that there is still a connection and the maker then fails to establish substreams when a protocol execution is triggered.

At this point we are not totally sure if this problem can be solved by configuring how the TCP connection is managed by `yamux`, or if we are not reacting to an event from the underlying stack that would notify us. This can be investigated, but it might be hard, and it is unclear if we can always rely on this.

So, it might still be better, to make the `Endpoint` resilient to "missed" connection drops, where we keep trying to open a substream but fail.

---

Some notes on solution design:

We did make an effort to overcome this problem before, by introducing an failure counter, see #2175,  but removed this feature because it had unwanted side effects (see #2207). I think the overall idea of this feature was still good, but we just need to design it in a better way.

### PR DESCRIPTION
**Pull request by luckysori**
Fix #2554.

We already categorised certain errors emitted by yamux as `BadConnection` errors. It therefore makes sense to drop the
connection to a peer if we get one of those errors when trying to open a substream to them.

---

We don't necessarily have to close #2554 if we merge this. But this might be good enough!

### CODE REVIEW

File: xtra-libp2p/src/endpoint.rs [hunk 1]
```diff
@@ -530,26 +530,40 @@ impl Endpoint {
...
+                let res =
+                    Self::open_substream(control, peer_id, protocols.clone(), connection_timeout)
+                        .await;
+
+                if let Err(Error::BadConnection(e)) = &res {
+                    tracing::debug!(
+                        %peer_id,
+                        "Disconnecting peer due to yamux connection error when opening substream: {e}"
+                    );
+                    let _ = this.send_async_safe(Disconnect(peer_id)).await;
```
Comment (Restioson) [inline xtra-libp2p/src/endpoint.rs]: Should this not be a send_async_next (I forget the exact name)? Alternatively, could it just be `self.handle(Disconnect(peer_id), ctx).await`?

Comment (luckysori) [reply xtra-libp2p/src/endpoint.rs]: I like your first suggestion, primarily because then we don't have to ignore the result.

Do you think it is important that we give this message priority though? I suppose the earlier we get it processed the quicker we'll stop using the faulty connection. But it didn't strike me as something that needed to be done immediately.

Comment (Restioson) [reply xtra-libp2p/src/endpoint.rs]: I think it makes sense to give priority in case the next queued message was a Ping message or similar - in that case we will skip the message sending to the disconnected peer

**Review by da-kami — APPROVED** [review]
I think this is a valuable change, let's see how it behaves on testnet. 
For testing we should start multiple takers to ensure we are not dropping the connection repeatedly and kill the `maker`.

I had a look at `yamux::ConnectionError` which is what is mapped to `BadConnection` and I think all instances of this error should result in dropping the connection:

```
pub enum ConnectionError {
    /// An underlying I/O error occured.
    Io(std::io::Error),
    /// Decoding a Yamux message frame failed.
    Decode(FrameDecodeError),
    /// The whole range of stream IDs has been used up.
    NoMoreStreamIds,
    /// An operation fails because the connection is closed.
    Closed,
    /// Too many streams are open, so no further ones can be opened at this time.
    TooManyStreams,
}
```

As far as I could see unsupported protocols are not mapped into this error, which is what kept us from dropping the connection before. I think `BadConnection` is thus save to be dropped!

File: xtra-libp2p/src/endpoint.rs [hunk 2]
```diff
@@ -530,26 +530,40 @@ impl Endpoint {
...
-                    Self::open_substream(control, peer, protocols.clone(), connection_timeout)
-                        .await?;
+                let res =
+                    Self::open_substream(control, peer_id, protocols.clone(), connection_timeout)
+                        .await;
+
+                if let Err(Error::BadConnection(e)) = &res {
+                    tracing::debug!(
+                        %peer_id,
+                        "Disconnecting peer due to yamux connection error when opening substream: {e}"
```
Comment (Restioson) [inline xtra-libp2p/src/endpoint.rs:561]: I missed this in the initial review, but I wonder if it could be useful to add this as an `err` field (or maybe some derivative of it, like the error kind) to make it searchable in traces? This would not only apply here but in only places.

Comment (luckysori) [reply xtra-libp2p/src/endpoint.rs:561]: Is your general suggestion to move our typical printed errors in logs to the `tracing` fields? I think it's a good idea. But will we lose the ability to include causes using `anyhow` (with `{e:#}`)?
