### PR TITLE
Only process CFDs where we have a DLC

### LINKED ISSUE #298: Message handler failed: No DLC available when attestation was received
Logs:

```
2021-10-13 17:34:05  WARN Could not connect to the maker, retrying in 5s ...
2021-10-13 17:34:05  INFO Authentication details: username='maker' password='0fac8291a04e51c1a0459e82a36a084f45a4abffc9ddf5cc111c36370c30e52a'
2021-10-13 17:34:05  INFO Listening on 0.0.0.0:9999
2021-10-13 17:34:06  INFO Connected to BitMex realtime API
2021-10-13 17:34:08 DEBUG Fetching attestation for /x/BitMEX/BXBT/2021-10-13T00:00:00.price?n=20
2021-10-13 17:34:08  WARN 🔧 Configured for debug.
2021-10-13 17:34:08  WARN address: 127.0.0.1
2021-10-13 17:34:08  WARN port: 8001
2021-10-13 17:34:08  WARN workers: 8
2021-10-13 17:34:08  WARN ident: Rocket
2021-10-13 17:34:08  WARN limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
2021-10-13 17:34:08  WARN temp dir: /tmp
2021-10-13 17:34:08  WARN keep-alive: 5s
2021-10-13 17:34:08  WARN tls: disabled
2021-10-13 17:34:08  WARN shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
2021-10-13 17:34:08  WARN log level: normal
2021-10-13 17:34:08  WARN cli colors: true
2021-10-13 17:34:08  WARN 📬 Routes:
2021-10-13 17:34:08  WARN (index) GET /<_paths..> text/html
2021-10-13 17:34:08  WARN (dist) GET /assets/<file..>
2021-10-13 17:34:08  WARN (maker_feed) GET /api/feed
2021-10-13 17:34:08  WARN (get_health_check) GET /api/alive
2021-10-13 17:34:08  WARN (post_sell_order) POST /api/order/sell
2021-10-13 17:34:08  WARN (post_cfd_action) POST /api/cfd/<id>/<action>
2021-10-13 17:34:08  WARN 🥅 Catchers:
2021-10-13 17:34:08  WARN (unauthorized) 401
2021-10-13 17:34:08  WARN (unauthorized) /api 401
2021-10-13 17:34:08  WARN 📡 Fairings:
2021-10-13 17:34:08  WARN SQL migrations (ignite)
2021-10-13 17:34:08  WARN Shield (liftoff, response, singleton)
2021-10-13 17:34:08  WARN Create actors (ignite)
2021-10-13 17:34:08  WARN 'maker' Database Pool (ignite)
2021-10-13 17:34:08  INFO 🛡 Shield:
2021-10-13 17:34:08  WARN 🚀 Rocket has launched from http://127.0.0.1:8001
2021-10-13 17:34:08  INFO Fetched new attestation for /x/BitMEX/BXBT/2021-10-13T00:00:00.price?n=20
2021-10-13 17:34:08 DEBUG Learnt latest oracle attestation for event: /x/BitMEX/BXBT/2021-10-13T00:00:00.price?n=20
2021-10-13 17:34:09 ERROR Message handler failed: No DLC available when attestation was received
```

What did I do:

1. Open a new contract
2. Shutdown app
3. Wait > 24 hours
4. Start app

Latest CFD state is `OpenCommitted` and it has a DLC object.

### PR DESCRIPTION
**Pull request by thomaseizinger**
If we just `.context` on the Option, we break out of the loop early
and don't process the remaining items.

Fixes #298.

### CODE REVIEW

File: daemon/src/taker_cfd.rs [hunk 1]
```diff
@@ -633,16 +633,18 @@ impl Actor {
         );
 
         let mut conn = self.db.acquire().await?;
-        let cfds = load_cfds_by_oracle_event_id(attestation.id, &mut conn).await?;
+        let mut cfds = load_cfds_by_oracle_event_id(attestation.id, &mut conn).await?;
 
-        for mut cfd in cfds {
+        for (cfd, dlc) in cfds
+            .iter_mut()
+            .filter_map(|cfd| cfd.dlc().map(|dlc| (cfd, dlc)))
```
Comment (da-kami) [inline daemon/src/taker_cfd.rs:640]: what a beautiful brainfuck

**Review by da-kami — APPROVED** [review]

File: daemon/src/taker_cfd.rs (hunk 1 above)
Comment (thomaseizinger) [reply daemon/src/taker_cfd.rs:640]: Should have written it as:

```rust
for wtf in cfds
            .iter_mut()
            .filter_map(|cfd| cfd.dlc().map(|dlc| (cfd, dlc)))
```
