### PR TITLE
Fix `BitMexPriceEventId` derived implementations

### LINKED ISSUE #2769: Rollover failed: Expect event to exist in msg
Just saw this locally.

```
2022-08-29 06:28:11  INFO xtra_libp2p_rollover::current::taker: Rollover proposal got accepted order_id=3712a56e-9e0d-4662-a9e3-3f47f3f5af6a
2022-08-29 06:28:13  WARN fallible task handle_error{err=Expect event to exist in msg}: model::cfd: Rollover failed: Expect event to exist in msg order_id=3712a56e-9e0d-4662-a9e3-3f47f3f5af6a peer_id=Some(12D3KooWEsK2X8Tp24XtyWh7DM65VfwXtNH2cmfs2JsWmkmwKbV1)
2022-08-29 06:28:13  INFO fallible task handle_error{err=Expect event to exist in msg}:xtra_actor_request{actor_type=daemon::process_manager::Actor message_type=daemon::process_manager::Event}:xtra_message_handler:Handle Event: sqlite_db: Appended event to database event=RolloverFailed order_id=3712a56e-9e0d-4662-a9e3-3f47f3f5af6a
```

### PR DESCRIPTION
**Pull request by luckysori**
Fixes https://github.com/itchysats/itchysats/issues/2769.

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
Very good find.

File: model/src/payout_curve.rs [hunk 1]
```diff
@@ -221,7 +221,7 @@ impl Announcements {
     fn new(announcements: Vec<olivia::Announcement>) -> Result<Self> {
         let announcements = announcements
             .into_iter()
-            .sorted_by(|a, b| a.id.cmp(&b.id))
+            .sorted_by(|a, b| a.id.timestamp().cmp(&b.id.timestamp()))
```
Comment (da-kami) [inline model/src/payout_curve.rs:224]: 🤔 What does this mean for already existing positions once we roll this out? Will the system be able to match them correctly?

Comment (luckysori) [reply model/src/payout_curve.rs:224]: It is functionally equivalent, because we were ignoring all fields except for the timestamp in the previous derived implementations of `PartialOrd` and `Ord`.
