### PR TITLE
Prefetch announcement upon proposing rollover

### LINKED ISSUE #361: Accepted rollover proposal fails because announcement is not yet fetched
As per title.

Fix is likely to prefetch announcement already when sending rollover proposal and hope (:crossed_fingers:) that it is there by the time the maker accepts.

### PR DESCRIPTION
**Pull request by thomaseizinger**
Fixes #361.

### CODE REVIEW

File: daemon/src/taker_cfd.rs [hunk 1]
```diff
@@ -343,6 +317,40 @@ where
...
+            proposal.order_id,
+            UpdateCfdProposal::RollOverProposal {
+                proposal: proposal.clone(),
+                direction: SettlementKind::Outgoing,
+            },
+        );
+        self.send_pending_update_proposals()?;
+
+        // we are likely going to need this one
+        self.oracle_actor
```
Comment (da-kami) [inline daemon/src/taker_cfd.rs:341]: Shall we do this one earlier, so we don't insert pending things in case it fails? (it is `send`, so I suppose we know if it failed)

Comment (thomaseizinger) [reply daemon/src/taker_cfd.rs:341]: I can only fail if the actor is down which it really should never be.

Comment (da-kami) [reply daemon/src/taker_cfd.rs:341]: I've heard that before :D

**Review by da-kami — APPROVED** [review]
