### PR TITLE
Fix fee taker UI

### LINKED ISSUE #1242: Opening fee is not shown in `Confirm` dialog

### PR DESCRIPTION
**Pull request by da-kami**
Still needs some testing.

### CODE REVIEW

File: daemon/src/projection.rs [hunk 1]
```diff
@@ -812,9 +815,18 @@ impl From<Order> for CfdOrder {
...
-            funding_rate_hourly_percent: HourlyFundingRate::from(order.funding_rate).to_string(),
+            funding_rate_hourly_percent: HourlyFundingPercent::from(order.funding_rate).to_string(),
+            initial_funding_fee_per_parcel: calculate_funding_fee(
+                order.price,
+                parcel_size,
+                order.leverage,
+                order.funding_rate,
+                SETTLEMENT_INTERVAL.whole_hours(),
+            )
+            .expect("to be able to calculate funding fee")
```
Comment (da-kami) [inline daemon/src/projection.rs]: Should probably use a `TryFrom` to avoid this expect.

File: daemon/tests/happy_path.rs [hunk 2]
```diff
@@ -77,7 +77,7 @@ fn assert_eq_order(mut published: CfdOrder, received: CfdOrder) {
 
     // Hard-coded to match the dummy_new_order()
     assert_eq!(received.opening_fee.unwrap(), Amount::from_sat(2));
-    assert_eq!(received.funding_rate_hourly_percent, "0.001");
+    assert_eq!(received.funding_rate_hourly_percent, "0.00100");
```
Comment (da-kami) [inline daemon/tests/happy_path.rs:80]: Note to self: Why do we need these two additional zeros here? We should not fix the percentage but fix it in the UI...

File: daemon/src/projection.rs (hunk 1 above)
Comment (da-kami) [reply daemon/src/projection.rs]: I added https://github.com/itchysats/itchysats/pull/1254/commits/55b7b1dca664fa1cdb5725321caa354f2ded0667 to achieve this. Probably would be even better to report failure back to the caller. I think it *can* happen that this fails - if it fails, it will fail on the maker and taker side, so the order would be invalid on both sides.
The projection is the fist time we trigger this calculation for the per-parcel initial funding fee. Maybe a better strategy would be to actually add this to the `Order`  - or at least ensure it can be calculated when creating it. Happy for suggestions.

File: taker-frontend/src/App.tsx [hunk 3]
```diff
@@ -53,8 +53,11 @@ export const App = () => {
     const parcelSize = parseOptionalNumber(order?.parcel_size) || 0;
     const liquidationPrice = parseOptionalNumber(order?.liquidation_price);
     const marginPerParcel = order?.margin_per_parcel || 0;
-    const openingFee = order?.opening_fee || 0;
+    const leverage = order?.leverage || 0;
+    let openingFee = order?.opening_fee || 0;
```
Comment (bonomat) [inline taker-frontend/src/App.tsx]:
```suggestion
    const openingFee = order?.opening_fee || 0;
```

File: daemon/src/projection.rs [hunk 4]
```diff
@@ -760,6 +760,9 @@ pub struct CfdOrder {
     /// The funding rate fluctuates with market movements.
     pub funding_rate_hourly_percent: String,
 
+    #[serde(with = "::bdk::bitcoin::util::amount::serde::as_btc")]
+    pub initial_funding_fee_per_parcel: Amount,
```
Comment (bonomat) [inline daemon/src/projection.rs]: Can we move this below `pub parcel_size: Usd,` please? I think this would make it easier to read the file top down

File: taker-frontend/src/components/Trade.tsx [hunk 5]
```diff
@@ -109,11 +110,9 @@ export default function Trade({
 
     const margin = (quantity / parcelSize) * marginPerParcel;
 
-    const openingFee = (quantity / parcelSize) * openingFeePerParcel;
+    let feeForFirstSettlementInterval = (quantity / parcelSize) * fundingFeePerParcel;
```
Comment (bonomat) [inline taker-frontend/src/components/Trade.tsx]:
```suggestion
    const feeForFirstSettlementInterval = (quantity / parcelSize) * fundingFeePerParcel;
```

File: taker-frontend/src/components/History.tsx [hunk 6]
```diff
@@ -154,8 +154,12 @@ const CfdDetails = ({ cfd, connectedToMaker, displayCloseButton }: CfdDetailsPro
                 <Table size="sm" variant={"unstyled"}>
                     <Tbody>
                         <Tr>
-                            <Td><Text as={"b"}>Total fees</Text></Td>
-                            <Td textAlign="right"><BitcoinAmount btc={cfd.accumulated_fees} /></Td>
+                            <Td><Text as={"b"}>Estimated fees</Text></Td>
+                            <Td textAlign="right">
+                                <Tooltip label={"includes transaction fees"} placement={"right"}>
```
Comment (bonomat) [inline taker-frontend/src/components/History.tsx]: 🚧 Not sure why but this tooltip seems to break everything. Removing it makes the side load again.

```
Uncaught Error: React.Children.only expected to receive a single React element child.
    onlyChild React
    Tooltip chakra-ui-tooltip.esm.js:290
    React 12
    unstable_runWithPriority scheduler.development.js:468
    React 5
    listener useLatestEvent.ts:13
    useLatestEvent useLatestEvent.ts:16
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 4
    unstable_runWithPriority scheduler.development.js:468
    React 6
    <anonymous> main.tsx:9
react.development.js:1139:12
```

If you move the tooltip around `Td` it works.

**Review by bonomat — DISMISSED** [review]
One thing to fix please.

File: taker-frontend/src/components/History.tsx (hunk 6 above)
Comment (da-kami) [reply taker-frontend/src/components/History.tsx]: Oh, interesting. On my machine it works, but I generally had some trouble with chakra tooltips causing errors; so far it was not permanent errors though, i.e. the page loaded, but the logs showed an error when hovering over the tooltip. 

I'll move it around the `Td` if that helps.

File: daemon/src/projection.rs [hunk 7]
```diff
@@ -810,12 +826,21 @@ impl From<Order> for CfdOrder {
                 .settlement_interval
                 .whole_seconds()
                 .try_into()
-                .expect("settlement_time_interval_hours is always positive number"),
+                .context("unable to convert settlement interval")?,
```
Comment (thomaseizinger) [inline daemon/src/projection.rs:829]: Previously, we solved this by making the specific field that failed an `Option` rendering it as a `Skeleton` in the UI.

File: daemon/src/projection.rs [hunk 8]
```diff
@@ -810,12 +826,21 @@ impl From<Order> for CfdOrder {
...
-        }
+            funding_rate_hourly_percent: HourlyFundingPercent::from(order.funding_rate).to_string(),
+            initial_funding_fee_per_parcel: calculate_funding_fee(
+                order.price,
+                parcel_size,
+                order.leverage,
+                order.funding_rate,
+                SETTLEMENT_INTERVAL.whole_hours(),
+            )
+            .context("unable to calcualte initial funding fee")?
```
Comment (thomaseizinger) [inline daemon/src/projection.rs:841]: Do we have test cases that show when this can fail?

File: taker-frontend/src/App.tsx [hunk 9]
```diff
@@ -53,8 +53,11 @@ export const App = () => {
     const parcelSize = parseOptionalNumber(order?.parcel_size) || 0;
     const liquidationPrice = parseOptionalNumber(order?.liquidation_price);
     const marginPerParcel = order?.margin_per_parcel || 0;
-    const openingFee = order?.opening_fee || 0;
+    const leverage = order?.leverage || 0;
```
Comment (thomaseizinger) [inline taker-frontend/src/App.tsx:56]: If you default this to 0 now, you should change the `Props` type of `Trade` to no longer accept an optional `leverage` to get more type safety.

File: daemon/src/projection.rs [hunk 10]
```diff
@@ -670,7 +670,18 @@ impl Actor {
     }
 
     fn handle(&mut self, msg: Update<Option<Order>>) {
-        let _ = self.tx.order.send(msg.0.map(|x| x.into()));
+        let order = match msg.0 {
+            None => None,
+            Some(order) => match TryInto::<CfdOrder>::try_into(order) {
+                Ok(order) => Some(order),
+                Err(e) => {
+                    tracing::warn!("Unable to convert order: {:#}", e);
```
Comment (thomaseizinger) [inline daemon/src/projection.rs]:
```suggestion
                    tracing::warn!("Unable to convert order: {e:#}");
```

File: taker-frontend/src/components/History.tsx (hunk 6 above)
Comment (da-kami) [reply taker-frontend/src/components/History.tsx]: If I wrap it around the `Td` I get this error (that is not fatal though):

```
react-dom.development.js:67 Warning: validateDOMNesting(...): <span> cannot appear as a child of <tr>.
    at span
    at DefaultPortal2 (http://localhost:3000/node_modules/.vite/@chakra-ui_react.js?v=8421fb55:1401:36)
    at Portal (http://localhost:3000/node_modules/.vite/@chakra-ui_react.js?v=8421fb55:1464:28)
    at PresenceChild (http://localhost:3000/node_modules/.vite/chunk-QRD5N5TB.js?v=8421fb55:6477:21)
    at AnimatePresence (http://localhost:3000/node_modules/.vite/chunk-QRD5N5TB.js?v=8421fb55:6556:21)
    at http://localhost:3000/node_modules/.vite/@chakra-ui_react.js?v=8421fb55:20820:17
...
```

It seems Chakra somehow has a `span` for the tooltip which is not allowed as sub-element in html tables.
When navigating through the dom-tree in the browser I was unable to find the span that causes the problem though. 

The chakra documentation states

> If the children of Tooltip is a string, we wrap with in a span with tabIndex set to 0, to ensure it meets the accessibility requirements.

https://chakra-ui.com/docs/overlay/tooltip#usage

But I don't think that is the case here. I think we should report this as bug upstream.

**Review by thomaseizinger — COMMENTED** [review]
Some comments, haven't tested it.

Would be nice to have unit tests for `calculate_funding_fee` that show us, when exactly this can fail so we can make a better judgement on whether the complexity of handling the error is worthwhile.

File: daemon/src/projection.rs (hunk 8 above)
Comment (da-kami) [reply daemon/src/projection.rs:841]: https://github.com/itchysats/itchysats/pull/1255 should cover this, but will need to be adapted to my changes.
I'd say this is not critical for the release and can be done later.

File: daemon/src/projection.rs (hunk 7 above)
Comment (da-kami) [reply daemon/src/projection.rs:829]: I'd say this is not critical for the release and can be done later.
