### PR TITLE
Calculate payouts correctly

### LINKED ISSUE #1580: Calculate the payout correcly when the taker is short
As @luckysori pointed out we are not using https://github.com/itchysats/itchysats/blob/long-story-short/model/src/cfd.rs#L1900-L1922 in the code, which means that the payout for taker=short/maker=long is calculated wrongly. 

Proposal for fix:
- Create failing test(s): Extend the tests to cover taker=short/maker=long and assert on the values so we know that this is wrong 
- Create another abstraction on top of `calculate_payouts_long_taker` and `calculate_payouts_short_taker` that knows about the role and then delegate to the functions as necessary. I thought about actually having this functionality on the `model::Cfd` - might be worth exploring - but the contract_setup currently does not know about the `model::Cfd`

### PR DESCRIPTION
**Pull request by luckysori**
Fixes #1580.

### CODE REVIEW

File: model/src/cfd.rs [hunk 1]
```diff
@@ -918,11 +918,15 @@ impl Cfd {
         proposal: SettlementProposal,
         sig_taker: Signature,
     ) -> Result<CollaborativeSettlement> {
+        anyhow::ensure!(
+            self.role == Role::Maker,
+            "Only the maker can create complete collaborative settlement signing"
+        );
```
Comment (klochowicz) [inline model/src/cfd.rs]: I'd go even further by using `assert_debug` or `assert` perhaps - it's not a runtime error, it's a bug in our code if this ever happens, therefore I'd avoid gracefully handling this.

I'm happy also to settle on this one for the time being as it's a giant improvement guarding us from actually doing it when we shouldn't

File: daemon/src/maker_cfd.rs [hunk 2]
```diff
@@ -271,8 +271,13 @@ where
     ) -> Result<()> {
         tracing::info!(%order_id, %taker_id,  "Received rollover proposal from taker");
 
+        let mut conn = self.db.acquire().await?;
+        let cfd = load_cfd(order_id, &mut conn).await?;
+        let position = cfd.position();
```
Comment (klochowicz) [inline daemon/src/maker_cfd.rs]: this would conflict with: #1585 - suggest syncing with @thomaseizinger

File: daemon-tests/src/lib.rs [hunk 3]
```diff
@@ -361,10 +361,10 @@ impl Taker {
         }
     }
 
-    pub async fn trigger_rollover(&self, id: OrderId) {
+    pub async fn trigger_rollover(&self, order_id: OrderId, position: Position) {
```
Comment (klochowicz) [inline daemon-tests/src/lib.rs]: I thought for a while that this is pretty weird API to need to pass the position, but then realised it's just for the tests..... 😌

**Review by klochowicz — APPROVED** [review]
nice job! both with cleanups & features 👍

File: daemon-tests/src/lib.rs (hunk 3 above)
Comment (luckysori) [reply daemon-tests/src/lib.rs]: To be fair it's still pretty weird to me, but I couldn't come up with anything better at this stage.

File: daemon/src/rollover_taker.rs [hunk 4]
```diff
@@ -128,6 +132,7 @@ impl Actor {
             (self.oracle_pk, announcement),
             rollover_params,
             Role::Taker,
+            self.position,
```
Comment (thomaseizinger) [inline daemon/src/rollover_taker.rs]: I'd suggest returning the position from `handle_rollover_accepted_taker` if you need it here.

File: daemon/src/maker_cfd.rs (hunk 2 above)
Comment (thomaseizinger) [reply daemon/src/maker_cfd.rs]: Yes, lets not do this please.

File: model/src/cfd.rs [hunk 5]
```diff
@@ -1890,11 +1897,18 @@ pub fn calculate_payouts_long_taker(
...
+            .collect(),
+        (Position::Short, Role::Taker) | (Position::Long, Role::Maker) => payouts
+            .into_iter()
+            .map(|payout| generate_payouts(payout.range, payout.long, payout.short))
+            .flatten_ok()
+            .collect(),
+    }
 }
 
 pub fn calculate_payouts_short_taker(
```
Comment (thomaseizinger) [inline model/src/cfd.rs]: Do we still need this function now?

File: daemon-tests/src/lib.rs (hunk 3 above)
Comment (thomaseizinger) [reply daemon-tests/src/lib.rs]: I think this might go away if we return the position together with the event from the command handler?

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Thanks for bringing over the refactoring commits. One minor change I'd like to see otherwise LGTM!

File: daemon/src/rollover_taker.rs (hunk 4 above)
Comment (luckysori) [reply daemon/src/rollover_taker.rs]: Thanks for the suggestion, that makes things a lot easier.

File: model/src/cfd.rs (hunk 1 above)
Comment (luckysori) [reply model/src/cfd.rs]: I think you're right. I went for `debug_assert`.

File: daemon/src/rollover_maker.rs [hunk 6]
```diff
@@ -52,6 +53,7 @@ struct RolloverFailed {
 
 pub struct Actor {
     order_id: OrderId,
+    position: Position,
```
Comment (thomaseizinger) [inline daemon/src/rollover_maker.rs]: This actor should also retrieve the position by returning it from `accept_rollover_proposal`.

File: daemon/src/setup_maker.rs [hunk 7]
```diff
@@ -101,6 +101,7 @@ impl Actor {
             self.build_party_params.clone_channel(),
             self.sign.clone_channel(),
             Role::Maker,
+            self.order.position_maker,
```
Comment (thomaseizinger) [inline daemon/src/setup_maker.rs]: To be consistent, you could also get the position from `start_contract_setup` here instead of passing it in through the `order.` Not sure what is cleaner.

File: daemon/src/rollover_maker.rs (hunk 6 above)
Comment (luckysori) [reply daemon/src/rollover_maker.rs]: You're right!!!!

File: daemon/src/setup_maker.rs (hunk 7 above)
Comment (luckysori) [reply daemon/src/setup_maker.rs]: It's simpler and more consistent that way because we don't have to pass any extra data to the `setup_taker.rs`.

File: model/src/cfd.rs [hunk 8]
```diff
@@ -940,7 +952,9 @@ impl Cfd {
             "Failed to propose collaborative settlement"
         );
 
-        let payout_curve = calculate_payouts_long_taker(
+        let payout_curve = calculate_payouts(
+            self.position,
+            self.role,
             self.initial_price,
             self.quantity,
             self.long_leverage,
```
Comment (da-kami) [inline model/src/cfd.rs:961]: was unable to comment on the line below...

We still always hard-code `Leverage::new(SHORT_LEVERAGE)` - this has to be change to `self.short_leverage` if I understand this correctly. 

Note that this is in multiple places!
I'd recommend removing the `SHORT_LEVERAGE` constant. The maker always being locked in to `Leverage::ONE` should already be correctly handled when constructing the `Cfd`.

**Review by da-kami — CHANGES_REQUESTED** [review]

**Review by thomaseizinger — APPROVED** [review]
Cool, happy with that! Thank you :)

File: model/src/cfd.rs (hunk 8 above)
Comment (thomaseizinger) [reply model/src/cfd.rs:961]: Nice catch!

Comment (luckysori) [reply model/src/cfd.rs:961]: Makes sense! I'll add a commit on top because this is not strictly related to assigning the payouts to the correct parties.

Comment (da-kami) [reply model/src/cfd.rs:961]: Would be great if you could remove the constant `SHORT_LEVERAGE` so we ensure that we don't use it anymore.

Comment (luckysori) [reply model/src/cfd.rs:961]: > Would be great if you could remove the constant `SHORT_LEVERAGE` so we ensure that we don't use it anymore.

Pretty sure I did!

Comment (da-kami) [reply model/src/cfd.rs:961]: Ah, yeah, sorry. Somhow did not see it in the commit 😅

**Review by da-kami — APPROVED** [review]
