### PR TITLE
Use `rollover` function in liquidation test for rollover

### LINKED ISSUE #2606: Flaky liquidation actor test
See test run: https://github.com/itchysats/itchysats/runs/7611016167?check_suite_focus=true
First seen on PR: https://github.com/itchysats/itchysats/pull/2599

Copied logs:

```
 running 1 test
2022-08-01T12:33:26.229461Z DEBUG given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate:start_both:Start maker: maker::actor_system: Maker actor system ready
2022-08-01T12:33:26.233879Z  INFO maker::connection: Listening on 127.0.0.1:41673
2022-08-01T12:33:26.245047Z  INFO Handle NewListenAddress: xtra_libp2p::endpoint: Listen address added address=/ip4/127.0.0.1/tcp/35813
2022-08-01T12:33:26.718108Z  INFO given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate:start_both:Start taker: daemon_tests: Connecting to maker /ip4/127.0.0.1/tcp/35813/p2p/12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1
2022-08-01T12:33:26.719799Z DEBUG given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate:start_both:Start taker:Create TakerActorSystem{n_payouts=200 connect_timeout_secs=10 environment=Test}: daemon: Taker actor system ready
2022-08-01T12:33:26.723040Z DEBUG online_status::Actor started: daemon::online_status: Online status watch actor started. Monitoring for peer id changes: PeerId("12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1")
2022-08-01T12:33:26.723743Z DEBUG Start dialer actor: xtra_libp2p::dialer: Starting dialer actor
2022-08-01T12:33:26.725844Z DEBUG connect: daemon::connection: No connection to the maker
2022-08-01T12:33:26.727049Z DEBUG connect:Handle Connect: daemon::connection: Connecting to maker address=127.0.0.1:41673
2022-08-01T12:33:26.748658Z DEBUG maker::connection: Upgrade new connection taker_address=127.0.0.1:45102
2022-08-01T12:33:26.762425Z DEBUG responder_handshake: daemon::noise: Noise protocol responder handshake is complete
2022-08-01T12:33:26.767026Z DEBUG connect:Handle Connect:initiator_handshake: daemon::noise: Noise protocol initiator handshake is complete
2022-08-01T12:33:26.781836Z  INFO Handle ConnectionReady: maker::connection: Connection is ready taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 taker_address=127.0.0.1:45102 wire_version=2.1.0 daemon_version=0.1.0 environment=Test peer_id=Some(12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P)
2022-08-01T12:33:26.784219Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:26.784954Z TRACE Handle TakerConnected:Handle TakerMessage: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::CurrentOffers"
2022-08-01T12:33:26.790300Z  INFO connect:Handle Connect: daemon::connection: Received Hello message from maker maker_identity=11ad505a586a5f4d64ed3164589e3adc206f5dd4434cab7f8a668ef2ac481221 actual_version=2.1.0
2022-08-01T12:33:26.790451Z  INFO connect:Handle Connect: daemon::connection: Established connection to maker address=127.0.0.1:41673
2022-08-01T12:33:26.796300Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:26.796710Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::CurrentOffers"
2022-08-01T12:33:26.799617Z  INFO Handle NewConnection: xtra_libp2p::endpoint: Connection established peer=12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P
2022-08-01T12:33:26.804075Z  INFO Start dialer actor:Handle Dial:dial:connect:Handle Connect:Dial new connection:Handle NewConnection: xtra_libp2p::endpoint: Connection established peer=12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1
2022-08-01T12:33:26.807373Z DEBUG Start dialer actor:Handle Dial:dial:connect:Handle Connect:Dial new connection:Handle NewConnection:Handle endpoint :: ConnectionEstablished: daemon::online_status: Adding newly established connection to online_status: PeerId("12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1")
2022-08-01T12:33:26.859714Z  INFO Handle IdentifyMsgReceived: daemon::identify::dialer: New identify message received peer_id=12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P daemon_version=0.1.0 environment=Test wire_version=0.3.0
2022-08-01T12:33:26.905144Z  INFO Handle IdentifyMsgReceived: daemon::identify::dialer: New identify message received peer_id=12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1 daemon_version=0.1.0 environment=Unknown wire_version=0.3.0
2022-08-01T12:33:26.907114Z TRACE given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate:Handle OfferParams:Handle BroadcastOffers:Broadcast offers to taker: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::CurrentOffers"
2022-08-01T12:33:26.911344Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::CurrentOffers"
2022-08-01T12:33:26.951925Z  INFO daemon::order::taker: Placing order order=PlaceOrder { id: OrderId(0695310d-3c2e-4ef6-a7ab-048812029579), offer: Offer { id: OrderId(0a91af5e-cb56-496d-ab93-2cb228b3be88), trading_pair: BtcUsd, position_maker: Short, price: Price(394096), min_quantity: Usd(100), max_quantity: Usd(1000), leverage_taker: Leverage(2), leverage_choices: [Leverage(2)], creation_timestamp_maker: Timestamp(1659357206), settlement_interval: Duration { seconds: 86400, nanoseconds: 0 }, origin: Theirs, oracle_event_id: BitMexPriceEventId { timestamp: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 214 }, time: Time { hour: 13, minute: 0, second: 0, nanosecond: 0 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }, digits: 20 }, tx_fee_rate: TxFeeRate(1), funding_rate: FundingRate(0.00024), opening_fee: OpeningFee { fee: Amount(0.00000002 BTC) } }, quantity: Usd(100), leverage: Leverage(2), maker_peer_id: PeerId("12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1"), maker_identity: Identity(PublicKey(MontgomeryPoint([17, 173, 80, 90, 88, 106, 95, 77, 100, 237, 49, 100, 88, 158, 58, 220, 32, 111, 93, 212, 67, 76, 171, 127, 138, 102, 142, 242, 172, 72, 18, 33]))) }
2022-08-01T12:33:26.985964Z  INFO Register new inbound substream{substream=NewInboundSubstream { peer: PeerId("12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P"), stream: Substream { inner: Negotiated { state: Completed { io: Stream { id: 3, connection: b168fa15 } } } } }}:Handle NewInboundSubstream: daemon::order::maker: Taker wants to place an order taker=12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P quantity=100 order_id=0695310d-3c2e-4ef6-a7ab-048812029579
2022-08-01T12:33:27.014527Z DEBUG given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate:Handle AcceptOrder:Handle Decision: daemon::order::maker: Instructed to Accept order 0695310d-3c2e-4ef6-a7ab-048812029579
2022-08-01T12:33:27.014782Z  INFO daemon::order::maker: Order accepted taker=12D3KooWE2ond2RuV7xb16E7NwmABUx6McmuvSXWVZefWveZpC5P quantity=100 order_id=0695310d-3c2e-4ef6-a7ab-048812029579
2022-08-01T12:33:27.016040Z  INFO daemon::order::taker: Order accepted order_id=0695310d-3c2e-4ef6-a7ab-048812029579 maker_peer_id=12D3KooWRyHFsHo72WWsFqBkeN1m1R9CvWPApu9dEwmMqVdXEyk1
2022-08-01T12:33:27.049775Z DEBUG Setup contract: daemon::setup_contract: setup_params=SetupParams { margin: Amount(0.00025375 BTC), counterparty_margin: Amount(0.00012687 BTC), counterparty_identity: Identity(PublicKey(MontgomeryPoint([104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 44, 32, 111, 104, 32, 119, 104, 97, 116, 32, 97, 32, 98, 101, 97, 117, 116, 105, 102, 117, 108]))), price: Price(394096), quantity: Usd(100), long_leverage: Leverage(2), short_leverage: Leverage(1), refund_timelock: 216, tx_fee_rate: TxFeeRate(1), fee_account: FeeAccount { balance: SignedAmount(-0.00000009 BTC), position: Short, role: Maker } } role=Maker position=Short n_payouts=200
2022-08-01T12:33:27.131288Z DEBUG Setup contract: daemon::setup_contract: setup_params=SetupParams { margin: Amount(0.00012687 BTC), counterparty_margin: Amount(0.00025375 BTC), counterparty_identity: Identity(PublicKey(MontgomeryPoint([17, 173, 80, 90, 88, 106, 95, 77, 100, 237, 49, 100, 88, 158, 58, 220, 32, 111, 93, 212, 67, 76, 171, 127, 138, 102, 142, 242, 172, 72, 18, 33]))), price: Price(394096), quantity: Usd(100), long_leverage: Leverage(2), short_leverage: Leverage(1), refund_timelock: 216, tx_fee_rate: TxFeeRate(1), fee_account: FeeAccount { balance: SignedAmount(0.00000009 BTC), position: Long, role: Taker } } role=Taker position=Long n_payouts=200
2022-08-01T12:33:27.207427Z  INFO Setup contract: daemon::setup_contract: Exchanged setup parameters
2022-08-01T12:33:27.277790Z  INFO Setup contract: daemon::setup_contract: Exchanged setup parameters
2022-08-01T12:33:31.788961Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:31.791090Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:36.791383Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:36.793192Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:33:36.894416Z  INFO Setup contract: daemon::setup_contract: Created CFD transactions
2022-08-01T12:33:37.346299Z  INFO Setup contract: daemon::setup_contract: Created CFD transactions
2022-08-01T12:33:51.670651Z  INFO Setup contract: daemon::setup_contract: Exchanged CFD transactions
2022-08-01T12:34:10.451381Z  INFO Setup contract: daemon::setup_contract: Exchanged CFD transactions
2022-08-01T12:34:10.470615Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:10.473807Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:15.473556Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:15.475264Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:20.476044Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:20.477294Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:25.478042Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:25.479503Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
test given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate has been running for over 60 seconds
2022-08-01T12:34:26.181055Z  INFO Setup contract: daemon::setup_contract: Verified all signatures
2022-08-01T12:34:26.321390Z  INFO Setup contract: daemon::setup_contract: Verified all signatures
2022-08-01T12:34:26.324338Z  INFO Setup contract: daemon::setup_contract: Exchanged signed lock transaction
2022-08-01T12:34:26.379857Z  INFO Setup contract: daemon::setup_contract: Exchanged signed lock transaction
2022-08-01T12:34:28.635311Z  INFO model::cfd: Contract setup was completed order_id=0695310d-3c2e-4ef6-a7ab-048812029579
2022-08-01T12:34:29.027184Z  INFO model::cfd: Contract setup was completed order_id=0695310d-3c2e-4ef6-a7ab-048812029579
2022-08-01T12:34:30.545696Z TRACE Handle SendHeartbeat: wire: Sending taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14 msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:30.549829Z TRACE Forward MakerStreamMessage:Handle MakerStreamMessage: wire: Received msg_name="MakerToTaker::Heartbeat"
2022-08-01T12:34:31.001906Z DEBUG maker::connection: Connection got dropped taker_id=98bfe1af2c3dae9187c47f7ded06428c334924a61518bf78a17cf6077224ba14
test given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate ... FAILED

failures:

failures:
    given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 65.26s


--- TRY 3 STDERR:                         daemon-tests::liquidation given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate ---
thread 'given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate' panicked at 'called `Option::unwrap()` on a `None` value', daemon-tests/tests/liquidation.rs:92:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by da-kami**
Fixes https://github.com/itchysats/itchysats/issues/2606

This makes it easier to avoid problems with awaiting states (...).
I think the functionality of the test did not change.

We could additionally opt to adapt/split-up `prepare_rollover` so we can re-use it. So far I have not done so.

### CODE REVIEW

File: daemon-tests/tests/liquidation.rs [hunk 1]
```diff
@@ -80,11 +78,15 @@ async fn given_rollover_when_oracle_attests_long_liquidation_price_can_liquidate
...
-        .await;
+    rollover(
+        &mut maker,
+        &mut taker,
+        order_id,
+        oracle_data_rollover.clone(),
+        None,
+        fee_calculator.complete_fee_for_rollover_hours(24),
+    )
+    .await;
```
Comment (luckysori) [inline daemon-tests/tests/liquidation.rs]: 🙃 I'm not too fond of this because it makes the test a bit more complicated with all this data that needs to be passed around needlessly (we don't actually care about all the things that are being asserted in the `rollover` helper in this test).

I did depend on this helper in a previous version too, but I purposely moved away from it. I would prefer to call `wait_next_state` a couple of times explicitly here to save you all the other changes in this patch and still fix the bug in the test.

Comment (luckysori) [reply daemon-tests/tests/liquidation.rs]: Alternatively, we could split the `rollover` helper into two, so that one purely helps you to execute the protocol (like the `open_cfd` helper) and the other helps you assert things (not needed here).

**Review by luckysori — COMMENTED** [review]
Thanks for fixing the bug!

I prefer something a bit more lightweight to keep the test simpler, but it's just my opinion and is not blocking.

File: daemon-tests/tests/liquidation.rs (hunk 1 above)
Comment (Restioson) [reply daemon-tests/tests/liquidation.rs]: > we don't actually care about all the things that are being asserted in the rollover helper in this test

Is this worth worrying about? On the one hand, the tests are a bit less isolated (i.e if you break rollover, this is guaranteed to break too), but on the other hand it possibly extends the level of integration in the tests (if you break rollover subtly in a way that does not cause the test to fail for whatever reason, this test will still fail).

Comment (luckysori) [reply daemon-tests/tests/liquidation.rs]: > Is this worth worrying about?

I worry about it because all the needless complexity in the test makes it harder to understand and maintain for us in the future. As an example: why is this test talking about a `fee_calculator`, when none of that matters for what we're trying to verify here?

> On the one hand, the tests are a bit less isolated (i.e if you break rollover, this is guaranteed to break too)

I actually don't care so much about the fact that this test will fail when rollover is broken. In an ideal world we wouldn't have to deal with that minimal noise, but I can happily live with that.

> but on the other hand it possibly extends the level of integration in the tests (if you break rollover subtly in a way that does not cause the test to fail for whatever reason, this test will still fail)

This can be a valid argument depending on the case. We have some places where we check that rollover works after something new has happened (for example, after retrying a rollover so that the taker can catch up), and I think that's a good idea.

But here there is nothing to verify: we are running a regular contract setup and rollover as part of the _arrange_ phase of the test.

Comment (da-kami) [reply daemon-tests/tests/liquidation.rs]: > I'm not too fond of this because it makes the test a bit more complicated with all this data that needs to be passed around needlessly (we don't actually care about all the things that are being asserted in the rollover helper in this test).

I generally agree with this, and I am not a fan or introducing the `fee_calculator` into the liquidation tests. I will see to split the rollover function. 
Besides that I think it is great to have an abstraction for "do a rollover" in the tests, that can be used by tests other than the pure rollover tests. But I think you don't have a problem with that :)

Comment (da-kami) [reply daemon-tests/tests/liquidation.rs]: Note: I opted to only assert on the fees in separation, otherwise the rollover tests would get more complicated which I don't like. I think it is fair to keep some assertions in the `rollover` function. It's less code like this, but we use some assertions in tests that actually don't really care about these particular assertions. I think this is acceptable.

Additionally I generally improved the API for calling a rollover, there is no overhead for the liquidation test now, and the rollover tests read nicer as well I feel.

File: daemon-tests/src/lib.rs [hunk 2]
```diff
@@ -812,10 +826,14 @@ impl Taker {
...
 
-    pub fn latest_fees(&mut self) -> CompleteFee {
+    pub fn latest_complete_fee(&mut self) -> CompleteFee {
         self.first_cfd().aggregated().latest_fees()
     }
 
+    pub fn latest_fees(&mut self) -> SignedAmount {
+        self.first_cfd().accumulated_fees
+    }
+
```
Comment (luckysori) [inline daemon-tests/src/lib.rs]: 🔧 Could we document these methods? I have a hard time understanding why we need two different methods.

**Review by luckysori — APPROVED** [review]
Thank you so much for incorporating my feedback. I much prefer this version ☺️

File: daemon-tests/src/lib.rs (hunk 2 above)
Comment (da-kami) [reply daemon-tests/src/lib.rs]: I think the underlying problem is actually how `projection::Cfd` is modeled and how we expose values there. I will see to rename the convenience accessors in the tests for now and can add a comment if it helps. 
I thought about creating only one accessor for the test and then map around, but that's adds annoying conversion logic to the test 😅

**Comment by da-kami** [comment]
Given the current CI failure my fix seems to be not enough. 
I was unable to reproduce the failure locally, it appears the tests are still flaky. 

Possibly related to https://github.com/itchysats/itchysats/pull/2610

**Comment by luckysori** [comment]
> Given the current CI failure my fix seems to be not enough. I was unable to reproduce the failure locally, it appears the tests are still flaky.

The failure we see on CI is not the same one you fixed. I think your fix is fine.

> Possibly related to #2610

I don't understand how, but by all means revert that change. I would like to eventually get rid of the arbitrary sleeps, but maybe they're still sneakily necessary.

**Comment by da-kami** [comment]
> > Given the current CI failure my fix seems to be not enough. I was unable to reproduce the failure locally, it appears the tests are still flaky.
> 
> The failure we see on CI is not the same one you fixed. I think your fix is fine.
> 

Thanks for the late response!
Yeah, I figured it was a different scenario.

> > Possibly related to #2610
> 
> I don't understand how, but by all means revert that change. I would like to eventually get rid of the arbitrary sleeps, but maybe they're still sneakily necessary.

I don't think I will unless we see more failures. I think we should get to the bottom of *why* these sleeps are needed if they are actually needed. I also wanted to remove them in the past.
