### PR TITLE
Unlock wallet UTXOs after sufficient time has passed

### LINKED ISSUE #1135: Unlock temporarily locked UTXOs on failed contract setup
1. Include failed transaction in event
2. Extract inputs from transaction
3. Ping wallet actor to unlock UTXOs

### PR DESCRIPTION
**Pull request by luckysori**
Fixes #1135.

Most of what was changed with the first 3 patches ended up being unnecessary, so we can drop it if it's unwanted. The main benefit of those changes was to be able to write the test in ff69a50196254056f6690755933fe53c1222943d.

### CODE REVIEW

File: daemon/src/wallet.rs [hunk 1]
```diff
@@ -345,17 +356,99 @@ where
...
+    inner: HashSet<(Instant, OutPoint)>,
+    time_to_lock: Duration,
+}
+
+impl LockedUtxos {
+    fn new(network: Network) -> Self {
+        let time_to_lock = match network {
+            Network::Bitcoin => Duration::from_secs(20 * 60),
+            Network::Testnet | Network::Signet | Network::Regtest => Duration::from_secs(2 * 60),
+        };
```
Comment (luckysori) [inline daemon/src/wallet.rs]: 👀 I didn't invest time into figuring out good values for these in case we decide to solve this whole issue differently. Suggestions are welcome.

**Review by thomaseizinger — APPROVED** [review]
Nice work!

I think we could have gotten away without a test on the actor level although it is nice to test the feature through the actor API :)

File: daemon/src/wallet.rs [hunk 2]
```diff
@@ -354,17 +356,70 @@ where
...
 
+struct LockedUtxos {
+    inner: HashSet<(Instant, OutPoint)>,
+    time_to_lock: Duration,
+}
+
+impl LockedUtxos {
+    fn new(network: Network) -> Self {
+        let time_to_lock = match network {
+            Network::Bitcoin => Duration::from_secs(20 * 60),
```
Comment (da-kami) [inline daemon/src/wallet.rs]: ❓ At the moment we only lock the UTXOs when creating a new DLC, i.e. during contract setup (but not rollover because we use the original lock). This is irrelevant for all spending transactions from lock.
Is what I am stating correct?

File: daemon/src/wallet.rs [hunk 3]
```diff
@@ -354,17 +356,70 @@ where
...
+
+        self.inner.extend(utxos);
+    }
+
+    /// Return the list of locked UTXOs.
+    ///
+    /// Before creating the list, it removes all elements which should
+    /// no longer be part of the set of locked UTXOs.
+    fn list(&mut self) -> Vec<OutPoint> {
+        self.remove_expired();
```
Comment (da-kami) [inline daemon/src/wallet.rs:393]: ❓ This removes the UTXOs that were actually spent (i.e. where a tx was published that spends them)?

**Review by da-kami — APPROVED** [review]
Nice! Just a few questions to make sure I understand it correctly.

File: daemon/src/wallet.rs (hunk 2 above)
Comment (luckysori) [reply daemon/src/wallet.rs]: Yes, you're right! We only use wallet UTXOs for the lock transaction, which is only constructed during contract setup.

File: daemon/src/wallet.rs (hunk 3 above)
Comment (luckysori) [reply daemon/src/wallet.rs:393]: Not quite. The code doesn't actually reason about whether a UTXO was spent or not. 

UTXOs are locked from the perspective of our wallet up to a time based on a configurable value `time_to_lock`. This `LockedUtxos` data structure will eventually unlock them if enough time has passed. Some of those locked UTXOs may have been used in transactions, but enough time should have passed that the wallet doesn't attempt to use them again (and if the wallet does it would just fail). Others were locked but never used because contract setup failed, so it is desirable to unlock them (this is the feature we're adding with this PR).

Comment (thomaseizinger) [reply daemon/src/wallet.rs:393]: We may want to couple this unlock time with our sync interval in some form.

Comment (luckysori) [reply daemon/src/wallet.rs:393]: Can you describe what you're suggesting in more detail, @thomaseizinger?

File: daemon/src/wallet.rs [hunk 4]
```diff
@@ -345,17 +356,113 @@ where
...
+    ///
+    /// We have chosen a value of 20 minutes to allow for 1 or 2
+    /// confirmations if the UTXO was actually used. This way we are
+    /// unlikely to attempt to reuse the same UTXO and compete with
+    /// one of our transactions in the mempool.
+    const TIME_TO_LOCK_MAINNET: Duration = Duration::from_secs(20 * 60);
+
+    /// The minimum time that must pass before a locked UTXO is
+    /// released on any of the Bitcoin test networks.
+    const TIME_TO_LOCK_TEST: Duration = Duration::from_secs(2 * 60);
```
Comment (luckysori) [inline daemon/src/wallet.rs]: @thomaseizinger @da-kami I didn't end up changing these values but I documented the reason why the mainnet values were chosen. Does this make sense to you?

File: daemon/src/wallet.rs (hunk 3 above)
Comment (thomaseizinger) [reply daemon/src/wallet.rs:393]: Whether or not it is safe to discard locked UTXOs depends on our sync picking up the new transactions (and thus marking it internally as spent. `LockedUtxos` only exists because we need to reliably bridge the time gap between signing a transaction and the UTXOs showing up during the sync.

If we set `time_to_lock` to something like 4 * sync_internal, we should be reasonable safe.

Comment (thomaseizinger) [reply daemon/src/wallet.rs:393]: Note that we do pick up UTXOs used by transactions in the mempool so we don't actually need to wait for a confirmation.

Comment (luckysori) [reply daemon/src/wallet.rs:393]: Thanks for the explanation, that makes sense to me now.

Basically, by setting the `time_to_lock` field to `4 * sync_interval` we're saying that we don't expect any locked UTXOs to end up being used if they were not picked up by the  wallet after 4 `sync_interval`s.

Comment (thomaseizinger) [reply daemon/src/wallet.rs:393]: > Basically, by setting the `time_to_lock` field to `4 * sync_interval` we're saying that we don't expect any locked UTXOs to end up being used if they were not picked up by the wallet after 4 `sync_interval`s.

Correct.

File: daemon/src/wallet.rs [hunk 5]
```diff
@@ -95,12 +99,20 @@ impl Actor {
             ElectrumBlockchain::from(client),
         )?;
 
+        // UTXOs chosen after coin selection will only be locked for a
+        // few wallet sync intervals. UTXOs which were actually
+        // included in published transactions should be marked as
+        // spent by the internal bdk wallet by then. UTXOs which ended
+        // up not being used are expected to be safe to be reused by
+        // then without incurring in double spend attempts.
+        let time_to_lock = SYNC_INTERVAL * 4;
```
Comment (luckysori) [inline daemon/src/wallet.rs:108]: @thomaseizinger: From what we previously discussed. I removed all logic based on Bitcoin networks accordingly.

**Comment by luckysori** [comment]
bors retry
