### PR TITLE
Remove unneeded event data in one query

### LINKED ISSUE #2070: Query loads all but last entry but should load all but last per CFD
I think the query below is not working as expected:

https://github.com/itchysats/itchysats/blob/b36cd30ece958ab861b08032787a41d4baa2dbd5/daemon/src/db/cull_old_dlcs.rs#L37-L54

It should load all events but the last one of _each cfd_ but what it does is it loads all but the _last overall_.

### PR DESCRIPTION
**Pull request by bonomat**
By using json_set we can manipulate the json within the DB. This allows us to have a single query which removes unneeded event data, i.e. RolloverCompleted events which have a succeeding RolloverCompleted event and ContractSetupCompleted events that also have a succeeding RolloverCompleted event.

Resolves #2070

First patch includes commit from #2072 and can be dropped later.

### CODE REVIEW

File: maker/src/actor_system.rs [hunk 1]
```diff
@@ -83,7 +84,10 @@ where
             + Handler<monitor::MonitorCetFinality>
             + Actor<Stop = ()>,
     {
+        let now = Instant::now();
+        tracing::info!("Culling started");
         futures::executor::block_on(db.cull_old_dlcs())?;
+        tracing::info!(sync_time_sec = %now.elapsed().as_secs(), "Culling done");
```
Comment (bonomat) [inline maker/src/actor_system.rs]: Removed in fixup

**Review by bonomat — COMMENTED** [review]
On the full maker db this query took ~60 seconds on my machine. On the second run it took ~10 seconds.

File: daemon/src/db/cull_old_dlcs.rs [hunk 2]
```diff
@@ -1,127 +1,82 @@
 use crate::db::Connection;
 use anyhow::Result;
-use model::EventKind;
 use sqlx::pool::PoolConnection;
 use sqlx::Sqlite;
 
 impl Connection {
+    /// Cull old cfd events
+    ///
+    /// This function removes old `dlc` data from events which are not needed anymore
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🙃 

```suggestion
    /// Cull DLC data from old events.
    ///
    /// This method modifies the `dlc` field of the JSON blobs stored in the `events` 
    /// table for all the rows which do not correspond to the most recent 
    /// `EventKind::ContractSetupCompleted` or `EventKind::RolloverCompleted` event 
    /// of a CFD.
```

File: daemon/src/db/cull_old_dlcs.rs [hunk 3]
```diff
@@ -1,127 +1,82 @@
...
-
-            event.map(|event| (id, event))
-        }))
-}
+    /// Cull old cfd rollover events which are not needed anymore
+    ///
+    /// We set the `dlc` field of events `RolloverCompleted` to null where the event is not the most
+    /// recent `RolloverCompleted` event.
+    async fn cull_rollover_completed(conn: &mut PoolConnection<Sqlite>) -> Result<()> {
+        let effected_rows = sqlx::query!(
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🔧 

```suggestion
        let affected_rows = sqlx::query!(
```

File: daemon/src/db/cull_old_dlcs.rs [hunk 4]
```diff
@@ -1,127 +1,82 @@
...
+                        select json_set(events.data, '$.dlc', null)
+                        from events as inner_events
+                        where inner_events.id = EVENTS.id 
+                    )
+                where name = 'RolloverCompleted'
+                  and id not in (
+                    select max(id) from EVENTS as inner_events
+                    where inner_events.cfd_id = EVENTS.cfd_id
+                      and inner_events.name = EVENTS.name
+                );
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: I'm sure you've tried it, but why doesn't something like

```suggestion
                where name = 'RolloverCompleted' OR name = 'ContractSetupCompleted'
                  and id not in (
                    select max(id) from EVENTS as inner_events
                    where inner_events.cfd_id = EVENTS.cfd_id
                      and inner_events.name = EVENTS.name
                );
```

work?

File: daemon/src/db/cull_old_dlcs.rs [hunk 5]
```diff
@@ -1,127 +1,82 @@
...
+                        where EVENTS.id = inner_events.id
+                    )
+                where name = 'ContractSetupCompleted'
+                  and cfd_id in (
+                    select distinct cfd_id from EVENTS as inner_events
+                        where inner_events.cfd_id = EVENTS.cfd_id
+                        and inner_events.name = 'RolloverCompleted'
+                    );
+            "#
+        )
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🔧 We normally use these constants for this.
```suggestion
                where name = $1
                  and cfd_id in (
                    select distinct cfd_id from EVENTS as inner_events
                        where inner_events.cfd_id = EVENTS.cfd_id
                        and inner_events.name = 'RolloverCompleted'
                    );
            "#,
            model::EventKind::CONTRACT_SETUP_COMPLETED_EVENT,
        )
```

File: daemon/src/db/cull_old_dlcs.rs [hunk 6]
```diff
@@ -149,16 +104,60 @@ mod tests {
...
+        let mut conn = db.inner.acquire().await.unwrap();
+        let mut db_tx = conn.begin().await.unwrap();
+        let events = load_cfd_events(&mut db_tx, cfd.id(), 0).await.unwrap();
+        db_tx.commit().await.unwrap();
+
+        assert_eq!(events[0].event, contract_setup_cloned,);
+    }
 
+    #[tokio::test]
+    async fn given_one_rollovers_when_cull_then_first_event_has_none_dlc_and_second_hassome_dlc() {
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🔧 
```suggestion
    async fn given_one_rollover_when_cull_then_first_event_has_none_dlc_and_second_has_some_dlc() {
```

**Comment by bonomat** [comment]
size optimization: 

before: 

```
5.3G
```

after
```
30M
```

File: daemon/src/db/cull_old_dlcs.rs [hunk 7]
```diff
@@ -149,16 +104,60 @@ mod tests {
...
+        db_tx.commit().await.unwrap();
+
+        assert!(matches!(
+            &events[0].event,
+            EventKind::ContractSetupCompleted { dlc: None, .. },
+        ));
+
+        assert!(matches!(
+            &events[1].event,
+            EventKind::RolloverCompleted { dlc: Some(_), .. },
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🔧 Daniel suggested to always check against the original here, like we do in the previous test.

File: daemon/src/db/cull_old_dlcs.rs [hunk 8]
```diff
@@ -180,7 +179,16 @@ mod tests {
             EventKind::RolloverCompleted { dlc: None, .. },
         ));
 
-        assert_eq!(events[2].event, most_recent_rollover);
+        assert!(matches!(
+            &events[2].event,
+            EventKind::RolloverCompleted { dlc: Some(_), .. },
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🔧 Same as above.

File: daemon/src/db/cull_old_dlcs.rs [hunk 9]
```diff
@@ -180,7 +179,16 @@ mod tests {
...
+        ));
+
+        let event0_timestamp = &events[0].timestamp;
+        let event1_timestamp = &events[1].timestamp;
+        let event2_timestamp = &events[2].timestamp;
+
+        assert!(event0_timestamp < event1_timestamp && event1_timestamp < event2_timestamp);
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🙃 I wouldn't test this here. This is testing a property of `load_cfd_events`: that the events returned are ordered. I would be happy to introduce a test in `db.rs` for this (in a separate commit if possible).

File: daemon/src/db/cull_old_dlcs.rs [hunk 10]
```diff
@@ -224,24 +229,46 @@ mod tests {
     }
 
     #[tokio::test]
-    async fn given_contract_setup_completed_when_cull_old_dlcs_then_dlc_is_some() {
+    async fn given_two_cfds_one_contract_setup_completed_other_rolled_over_both_culled_correctly() {
```
Comment (luckysori) [inline daemon/src/db/cull_old_dlcs.rs]: 🙃 
```suggestion
    async fn given_cfds_contract_setup_completed_and_cfd_rolled_over_then_both_culled_correctly() {
```

**Review by luckysori — APPROVED** [review]
Thanks for improving things! I had one question and a few minor suggestions. But LGTM!

File: daemon/src/db/cull_old_dlcs.rs (hunk 4 above)
Comment (bonomat) [reply daemon/src/db/cull_old_dlcs.rs]: Because if we only have `ContractSetupCompleted` but no `RolloverCompleted` yet we want to keep the dlc data.

Comment (luckysori) [reply daemon/src/db/cull_old_dlcs.rs]: Have you tried it? My crappy SQL brain compiler seems to think that it could work.

File: maker/src/actor_system.rs [hunk 11]
```diff
@@ -83,7 +84,10 @@ where
             + Handler<monitor::MonitorCetFinality>
             + Actor<Stop = ()>,
     {
+        let now = Instant::now();
+        tracing::info!("Culling started");
```
Comment (bonomat) [inline maker/src/actor_system.rs]: and yet again it appears 🙈

File: daemon/src/db/cull_old_dlcs.rs (hunk 4 above)
Comment (bonomat) [reply daemon/src/db/cull_old_dlcs.rs]: I tried, but maybe you can come up with a query that works? 

The second query looks slightly different than the first if you look closely: it checks if the `cfd_id` is  in the list of events where there is at least one `RolloverCompletedEvent`

**Review by luckysori — APPROVED** [review]
LGTM, thanks!

File: daemon/src/db/cull_old_dlcs.rs (hunk 4 above)
Comment (luckysori) [reply daemon/src/db/cull_old_dlcs.rs]: > The second query looks slightly different than the first if you look closely: it checks if the cfd_id is in the list of events where there is at least one RolloverCompletedEvent

True. My idea would be to do something very similar to what you do in the first one, but slightly modified so that it considers all contract-setup/rollover events and only keeps the most recent one (whether it is contract-setup or rollover). But there must be a flaw in how I imagine it working.

> I tried, but maybe you can come up with a query that works?

I invoke the other SQL expert @da-kami if he's curious 😛 And if this already works we can iterate on it later.
