### PR TITLE
Fix monitoring

### LINKED ISSUE #260: `Refunded` instead of `Closed`
Once a CET is confirmed we always get `CetFinality` and `RefundFinality`, this is very strange:

```
2021-10-08 21:41:37  INFO Bitcoin transaction reached monitoring target txid=677d5e79318aa6e8fe8fa3c3de299bb25a8ce530bb1a27fabb67108d81facf28 target=confirmed with 1 blocks current=confirmed with 1 blocks
2021-10-08 21:41:37  INFO Cfd state change event Monitor(CetFinality(OrderId(5d0d71aa-efbc-48a1-baf8-853f288fe14d)))
2021-10-08 21:41:37  INFO Bitcoin transaction reached monitoring target txid=543662c6d0de53ed7a3f71cb016e53daf3c1bee7a3fcb6c525b8917aa8189c6a target=confirmed with 1 blocks current=confirmed with 1 blocks
2021-10-08 21:41:37  INFO Cfd state change event Monitor(RefundFinality(OrderId(5d0d71aa-efbc-48a1-baf8-853f288fe14d)))
```

depending on which message from monitor actor is processed in cfd actor first we transition either to `Closed` or `Refunded` - but actually always are in a `Close` scenario (i.e. CET published and confirmed, Refund tx is never sent on chain).

### PR DESCRIPTION
**Pull request by da-kami**
In this protocol we *can* actually have transactions with the same script, hence, we have to handle the `GetHistoryRes` by `Txid`.
To make this easier to understand we group the `Vec<Vec<GetHistoryRes>>` by `Txid` into `HashMap<Txid, GetHistroyRes>`.
Note: The assumption is, that only `GetHistroyRes` is returned for the `Txid`+`Script` combination.

fixes #260

### CODE REVIEW

File: daemon/src/monitor.rs [hunk 1]
```diff
@@ -267,12 +267,37 @@ where
...
             .context("Failed to get script histories")?;
 
-        self.update_state(latest_block_height, histories).await?;
+        let mut histories_grouped_by_txid = HashMap::new();
+        for history in histories {
+            for response in history {
+                let txid = response.tx_hash;
+                let script = match txid_to_script.get(&txid) {
+                    None => {
+                        tracing::error!(
```
Comment (thomaseizinger) [inline daemon/src/monitor.rs]: Use `warn` here? `error` seems a bit drastic.

**Comment by da-kami** [comment]
Tested, but no test yet 🤪
I'd say we can still merge the fix and add the test on top of it (without logic changes).

File: daemon/src/monitor.rs [hunk 2]
```diff
@@ -298,30 +323,29 @@ where
...
-                                u32::try_from(last.height).expect("we checked that height is > 0"),
+        // 1. Decide new status based on script history
+        let new_status = self
+            .awaiting_status
+            .iter()
+            .map(|(key, _old_status)| {
+                let new_script_status = match histories.get(key) {
+                    None => ScriptStatus::Unseen,
+                    Some(history_entry) => {
+                        if history_entry.height <= 0 {
```
Comment (thomaseizinger) [inline daemon/src/monitor.rs:334]: This could be a match arm guard.

File: daemon/src/monitor.rs [hunk 3]
```diff
@@ -298,30 +323,29 @@ where
...
+                            ScriptStatus::InMempool
+                        } else {
+                            ScriptStatus::Confirmed(Confirmed::from_inclusion_and_latest_block(
```
Comment (thomaseizinger) [inline daemon/src/monitor.rs:337]: As a clean-up, I think it would make sense to get rid of this `Confirmed` struct and just inline the entire logic into `ScriptStatus`.

**Review by thomaseizinger — APPROVED** [review]
Thanks for investigating and fixing this!

**Review by thomaseizinger — APPROVED** [review]
Good work!

File: daemon/src/monitor.rs [hunk 4]
```diff
@@ -383,6 +383,12 @@ where
 
                     tracing::trace!("{} subscriptions reached their monitoring target, {} remaining for this script", reached_monitoring_target.len(), remaining.len());
 
+                    // TODO: When reaching finality of a final tx (CET, refund_tx,
+                    // collaborate_close_tx) we have to remove the remaining "competing"
+                    // transactions. This is not critical, but when fetching
+                    // `GetHistoryRes` by script we can have entries that we don't care about
+                    // anymore.
```
Comment (thomaseizinger) [inline daemon/src/monitor.rs:390]: Make this an issue please.

**Review by thomaseizinger — APPROVED** [review]

File: daemon/src/monitor.rs (hunk 4 above)
Comment (da-kami) [reply daemon/src/monitor.rs:390]: https://github.com/comit-network/hermes/issues/276
